// Package generator implements eventheader-gen.
package generator

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/build/constraint"
	"go/constant"
	"go/format"
	"go/importer"
	"go/parser"
	"go/printer"
	"go/token"
	"go/types"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/cataggar/LinuxTracepoints-Go/eventheader"
)

const (
	GeneratedMarker = "// Code generated by eventheader-gen; DO NOT EDIT."
	generatedSyntax = "// eventheader-gen syntax=1"
)

type Config struct {
	Types  []string
	Output string
	Tags   string
	Check  bool
	Dir    string
}

type Diagnostic struct {
	Position token.Position
	Message  string
}

func (d *Diagnostic) Error() string {
	if d.Position.IsValid() {
		return fmt.Sprintf("%s: eventheader-gen: %s", d.Position, d.Message)
	}
	return "eventheader-gen: " + d.Message
}

type packageInfo struct {
	Dir            string
	ImportPath     string
	Name           string
	GoFiles        []string
	CgoFiles       []string
	TestGoFiles    []string
	IgnoredGoFiles []string
}

type buildTarget struct {
	goos   string
	goarch string
}

type sourcePackage struct {
	fset               *token.FileSet
	info               packageInfo
	goarch             string
	files              []*ast.File
	testFiles          []*ast.File
	ignoredFiles       []*ast.File
	typeFiles          []*ast.File
	types              map[string]*typeDecl
	consts             map[string]constDecl
	decls              map[string]token.Pos
	constraints        map[*ast.File]string
	typeInfo           *types.Info
	outputPath         string
	outputConstraint   string
	analysisConstraint string
	knownOS            map[string]bool
	knownArch          map[string]bool
	targets            []buildTarget
}

type typeDecl struct {
	spec *ast.TypeSpec
	file *ast.File
}

type constDecl struct {
	expr ast.Expr
	typ  ast.Expr
	file *ast.File
}

type eventOptions struct {
	Name    string
	Level   uint8
	Keyword uint64
	Group   string
	ID      uint16
	Version uint8
	Tag     uint16
	Opcode  uint8
}

type field struct {
	GoName         string
	WireName       string
	Path           string
	Constructor    string
	Method         string
	BaseType       string
	Array          string
	Count          uint16
	Format         string
	Tag            uint16
	Children       []field
	Semantic       string
	NetType        string
	DirectArray    bool
	FixedOuter     bool
	ElementWise    bool
	Scratch        string
	ScratchBacking string
	OriginalType   ast.Expr
	Position       token.Pos
}

type event struct {
	TypeName   string
	Options    eventOptions
	Fields     []field
	Constraint string
	Position   token.Pos
}

type tagOptions struct {
	name     string
	skip     bool
	format   string
	encoding string
	tag      uint16
	tagSet   bool
	position token.Pos
}

var formatNames = map[string]string{
	"default": "FormatDefault", "unsigned": "FormatUnsignedInt",
	"signed": "FormatSignedInt", "hex": "FormatHexInt", "errno": "FormatErrno",
	"pid": "FormatPID", "time": "FormatTime", "boolean": "FormatBoolean",
	"float": "FormatFloat", "hexbytes": "FormatHexBytes", "string8": "FormatString8",
	"stringutf": "FormatStringUTF", "stringbom": "FormatStringUTFBOM",
	"xml": "FormatStringXML", "json": "FormatStringJSON", "uuid": "FormatUUID",
	"port": "FormatPort", "ip": "FormatIPAddress",
}

var opcodeNames = map[string]uint8{
	"info": 0, "activity-start": 1, "activity-stop": 2,
	"collection-start": 3, "collection-stop": 4, "extension": 5,
	"reply": 6, "resume": 7, "suspend": 8, "send": 9, "receive": 0xf0,
}

var levelNames = map[string]uint8{
	"critical": 1, "error": 2, "warning": 3, "information": 4, "verbose": 5,
}

func Generate(config Config) ([]byte, error) {
	if config.Dir == "" {
		config.Dir = "."
	}
	output := config.Output
	if output == "" {
		output = "eventheader_gen.go"
	}
	if output != "-" {
		if _, err := validateOutput(config.Dir, output); err != nil {
			return nil, err
		}
	}
	seen := make(map[string]bool)
	for _, name := range config.Types {
		if name == "" {
			return nil, errors.New("-type contains an empty type name")
		}
		if seen[name] {
			return nil, fmt.Errorf("-type repeats %q", name)
		}
		seen[name] = true
	}
	pkg, err := loadPackage(config.Dir, config.Tags, config.Output, config.Types)
	if err != nil {
		return nil, err
	}
	if len(config.Types) == 0 {
		config.Types, err = pkg.annotatedTypes()
		if err != nil {
			return nil, err
		}
		if len(config.Types) == 0 {
			return nil, errors.New("no //eventheader:event directives found")
		}
	}
	events := make([]event, 0, len(config.Types))
	for _, name := range config.Types {
		ev, err := pkg.analyzeEvent(name)
		if err != nil {
			return nil, err
		}
		events = append(events, ev)
	}
	if err := pkg.checkGeneratedCollisions(events); err != nil {
		return nil, err
	}
	constraint := events[0].Constraint
	for _, ev := range events[1:] {
		if !constraintsEquivalent(ev.Constraint, constraint, pkg.targets, pkg.knownOS, pkg.knownArch) {
			return nil, pkg.errorf(ev.Position,
				"selected event types have different build constraints; generate them to separate outputs")
		}
	}
	if pkg.outputConstraint != "" &&
		!constraintImplies(constraint, pkg.outputConstraint, pkg.targets, pkg.knownOS, pkg.knownArch) {
		return nil, pkg.errorf(events[0].Position,
			"output filename %q has build constraint %q that is not implied by event constraint %q",
			filepath.Base(config.Output), pkg.outputConstraint, constraintDescription(constraint))
	}
	return render(pkg.info.Name, constraint, events)
}

func Write(config Config) error {
	output := config.Output
	if output == "" {
		output = "eventheader_gen.go"
	}
	dir := config.Dir
	if dir == "" {
		dir = "."
	}
	var initial outputState
	var err error
	if output != "-" {
		initial, err = validateOutputState(dir, output)
		if err != nil {
			return err
		}
	}
	data, err := Generate(config)
	if err != nil {
		return err
	}
	if output == "-" {
		if config.Check {
			return errors.New("-check cannot be used with -output=-")
		}
		_, err := os.Stdout.Write(data)
		return err
	}
	return writeOutput(dir, initial, data, config.Check)
}

func writeOutput(dir string, initial outputState, data []byte, check bool) error {
	return writeOutputWithHooks(dir, initial, data, check, nil)
}

type replacementHooks struct {
	beforeCommit func()
	afterCommit  func()
}

func writeOutputWithHooks(
	dir string,
	initial outputState,
	data []byte,
	check bool,
	hooks *replacementHooks,
) error {
	output := initial.path
	unlock, err := acquireOutputLock(output)
	if err != nil {
		return err
	}
	defer unlock()

	current, err := readOutputState(output)
	if err != nil {
		return err
	}
	if check {
		if !current.exists {
			return fmt.Errorf("%s is missing; run eventheader-gen", output)
		}
		if !bytes.Equal(current.data, data) {
			return fmt.Errorf("%s is stale; run eventheader-gen", output)
		}
		return nil
	}
	if current.exists && bytes.Equal(current.data, data) {
		return nil
	}
	if !sameOutputState(initial, current) {
		return concurrentModificationError(output)
	}
	temp, err := os.CreateTemp(filepath.Dir(output), "."+filepath.Base(output)+".*")
	if err != nil {
		return err
	}
	tempName := temp.Name()
	removeTemp := true
	defer func() {
		if removeTemp {
			_ = os.Remove(tempName)
		}
	}()
	if err := temp.Chmod(0o644); err != nil {
		temp.Close()
		return err
	}
	if _, err := temp.Write(data); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Sync(); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	if !initial.exists {
		if hooks != nil && hooks.beforeCommit != nil {
			hooks.beforeCommit()
		}
		if err := os.Link(tempName, output); err != nil {
			if errors.Is(err, os.ErrExist) {
				return concurrentModificationError(output)
			}
			return fmt.Errorf("install generated output %q: %w", output, err)
		}
		return nil
	}

	preserveTemp, err := replaceExistingOutput(tempName, initial, hooks)
	if preserveTemp {
		removeTemp = false
	}
	return err
}

type outputState struct {
	path   string
	exists bool
	data   []byte
	info   os.FileInfo
}

func sameOutputState(left, right outputState) bool {
	if left.exists != right.exists {
		return false
	}
	if !left.exists {
		return true
	}
	return os.SameFile(left.info, right.info) && bytes.Equal(left.data, right.data)
}

func concurrentModificationError(output string) error {
	return fmt.Errorf("concurrent modification of %q: output changed during generation", output)
}

func loadPackage(dir, tags, outputFile string, selectedTypes []string) (*sourcePackage, error) {
	args := []string{"list", "-e", "-json"}
	if tags != "" {
		args = append(args, "-tags", tags)
	}
	args = append(args, ".")
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	output, err := cmd.Output()
	if err != nil {
		var exit *exec.ExitError
		if errors.As(err, &exit) {
			return nil, fmt.Errorf("go list: %s", strings.TrimSpace(string(exit.Stderr)))
		}
		return nil, fmt.Errorf("go list: %w", err)
	}
	var info packageInfo
	if err := json.Unmarshal(output, &info); err != nil {
		return nil, fmt.Errorf("decode go list output: %w", err)
	}
	goarchCommand := exec.Command("go", "env", "GOARCH")
	goarchCommand.Dir = dir
	goarchOutput, err := goarchCommand.Output()
	if err != nil {
		return nil, fmt.Errorf("go env GOARCH: %w", err)
	}
	goarch := strings.TrimSpace(string(goarchOutput))
	sizes := types.SizesFor("gc", goarch)
	if sizes == nil {
		return nil, fmt.Errorf("unsupported GOARCH %q", goarch)
	}
	pkg := &sourcePackage{
		fset: token.NewFileSet(), info: info, goarch: goarch, types: make(map[string]*typeDecl),
		consts: make(map[string]constDecl), decls: make(map[string]token.Pos),
		constraints: make(map[*ast.File]string),
	}
	knownOS, knownArch, targets, err := knownTargetNames(info.Dir)
	if err != nil {
		return nil, err
	}
	pkg.knownOS, pkg.knownArch, pkg.targets = knownOS, knownArch, targets
	if outputFile == "" {
		outputFile = "eventheader_gen.go"
	}
	var outputPath string
	if outputFile != "-" {
		outputPath, err = validateOutput(info.Dir, outputFile)
		if err != nil {
			return nil, err
		}
		expressions := filenameBuildConstraints(filepath.Base(outputFile), knownOS, knownArch)
		pkg.outputConstraint = combineBuildConstraints(expressions)
		pkg.outputPath = outputPath
	}
	cgoFiles := make(map[string]bool, len(info.CgoFiles))
	for _, name := range info.CgoFiles {
		cgoFiles[name] = true
	}
	for _, name := range append(info.GoFiles, info.CgoFiles...) {
		path := filepath.Join(info.Dir, name)
		isOutput := outputPath != "" && filepath.Clean(path) == outputPath
		if isOutput {
			continue
		}
		file, err := parser.ParseFile(pkg.fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		isStdoutOutput := outputFile == "-" && isEventheaderGenerated(file)
		if isStdoutOutput {
			if file != nil {
				pkg.typeFiles = append(pkg.typeFiles, file)
			}
			continue
		}
		pkg.typeFiles = append(pkg.typeFiles, file)
		buildConstraint, err := canonicalBuildConstraint(file, name, knownOS, knownArch)
		if err != nil {
			return nil, pkg.errorf(file.Pos(), "%v", err)
		}
		if cgoFiles[name] {
			expressions := []constraint.Expr{&constraint.TagExpr{Tag: "cgo"}}
			if explicit := parseBuildConstraint(buildConstraint); explicit != nil {
				expressions = append(expressions, explicit)
			}
			buildConstraint = combineBuildConstraints(expressions)
		}
		pkg.constraints[file] = buildConstraint
		pkg.files = append(pkg.files, file)
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok {
				if function, isFunction := decl.(*ast.FuncDecl); isFunction && function.Recv == nil {
					pkg.decls[function.Name.Name] = function.Name.Pos()
				}
				continue
			}
			if gen.Tok == token.TYPE {
				for _, item := range gen.Specs {
					spec := item.(*ast.TypeSpec)
					if previous := pkg.types[spec.Name.Name]; previous != nil {
						return nil, pkg.errorf(spec.Pos(), "type %s is declared more than once", spec.Name.Name)
					}
					pkg.types[spec.Name.Name] = &typeDecl{spec: spec, file: file}
					pkg.decls[spec.Name.Name] = spec.Name.Pos()
				}
			} else if gen.Tok == token.CONST {
				pkg.collectConstants(gen, file)
				for _, item := range gen.Specs {
					for _, name := range item.(*ast.ValueSpec).Names {
						pkg.decls[name.Name] = name.Pos()
					}
				}
			} else if gen.Tok == token.VAR {
				for _, item := range gen.Specs {
					for _, name := range item.(*ast.ValueSpec).Names {
						pkg.decls[name.Name] = name.Pos()
					}
				}
			}
		}
	}
	for _, name := range info.TestGoFiles {
		path := filepath.Join(info.Dir, name)
		if outputPath != "" && filepath.Clean(path) == outputPath {
			continue
		}
		file, err := parser.ParseFile(pkg.fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		if file.Name.Name != info.Name || (outputFile == "-" && isEventheaderGenerated(file)) {
			continue
		}
		buildConstraint, err := canonicalBuildConstraint(file, name, knownOS, knownArch)
		if err != nil {
			return nil, pkg.errorf(file.Pos(), "%v", err)
		}
		pkg.constraints[file] = buildConstraint
		pkg.testFiles = append(pkg.testFiles, file)
	}
	for _, name := range info.IgnoredGoFiles {
		path := filepath.Join(info.Dir, name)
		if outputPath != "" && filepath.Clean(path) == outputPath {
			continue
		}
		file, err := parser.ParseFile(pkg.fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		if file.Name.Name != info.Name || (outputFile == "-" && isEventheaderGenerated(file)) {
			continue
		}
		buildConstraint, err := canonicalBuildConstraint(file, name, knownOS, knownArch)
		if err != nil {
			return nil, pkg.errorf(file.Pos(), "%v", err)
		}
		if importsC(file) {
			expressions := []constraint.Expr{&constraint.TagExpr{Tag: "cgo"}}
			if explicit := parseBuildConstraint(buildConstraint); explicit != nil {
				expressions = append(expressions, explicit)
			}
			buildConstraint = combineBuildConstraints(expressions)
		}
		pkg.constraints[file] = buildConstraint
		pkg.ignoredFiles = append(pkg.ignoredFiles, file)
	}
	if len(selectedTypes) == 0 {
		selectedTypes, err = pkg.annotatedTypes()
		if err != nil {
			return nil, err
		}
	}
	if err := pkg.checkPredeclaredShadows(selectedTypes); err != nil {
		return nil, err
	}
	if err := pkg.checkSelectedGeneratedCollisions(selectedTypes); err != nil {
		return nil, err
	}
	if err := pkg.addSyntheticDeclarations(selectedTypes); err != nil {
		return nil, err
	}
	typeInfo, err := pkg.typeCheck(tags)
	if err != nil {
		return nil, err
	}
	pkg.typeInfo = typeInfo
	return pkg, nil
}

func isEventheaderGenerated(file *ast.File) bool {
	var headerGroups []*ast.CommentGroup
	for _, group := range file.Comments {
		if group.Pos() > file.Package {
			break
		}
		headerGroups = append(headerGroups, group)
	}
	if len(headerGroups) == 2 &&
		len(headerGroups[0].List) == 1 &&
		constraint.IsGoBuild(strings.TrimSpace(headerGroups[0].List[0].Text)) {
		headerGroups = headerGroups[1:]
	}
	return len(headerGroups) == 1 &&
		len(headerGroups[0].List) == 2 &&
		headerGroups[0].List[0].Text == GeneratedMarker &&
		headerGroups[0].List[1].Text == generatedSyntax
}

func validateOutput(packageDir, outputFile string) (string, error) {
	state, err := validateOutputState(packageDir, outputFile)
	return state.path, err
}

func validateOutputState(packageDir, outputFile string) (outputState, error) {
	base := filepath.Base(outputFile)
	if filepath.Ext(base) != ".go" || strings.HasSuffix(base, "_test.go") ||
		strings.HasPrefix(base, ".") || strings.HasPrefix(base, "_") {
		return outputState{}, fmt.Errorf("output %q must have a normal non-test .go basename", outputFile)
	}

	packageDir, err := filepath.Abs(packageDir)
	if err != nil {
		return outputState{}, fmt.Errorf("resolve source package directory: %w", err)
	}
	var outputPath string
	if filepath.IsAbs(outputFile) {
		outputPath = filepath.Clean(outputFile)
	} else {
		if filepath.Dir(outputFile) != "." {
			return outputState{}, fmt.Errorf("output %q must be directly inside the source package directory", outputFile)
		}
		outputPath = filepath.Join(packageDir, outputFile)
	}

	resolvedPackageDir, err := filepath.EvalSymlinks(packageDir)
	if err != nil {
		return outputState{}, fmt.Errorf("resolve source package directory: %w", err)
	}
	resolvedOutputDir, err := filepath.EvalSymlinks(filepath.Dir(outputPath))
	if err != nil {
		return outputState{}, fmt.Errorf("resolve output directory for %q: %w", outputFile, err)
	}
	if resolvedOutputDir != resolvedPackageDir {
		return outputState{}, fmt.Errorf("output %q must be directly inside the source package directory", outputFile)
	}

	resolvedOutputPath, resolveErr := filepath.EvalSymlinks(outputPath)
	if resolveErr == nil && filepath.Dir(resolvedOutputPath) != resolvedPackageDir {
		return outputState{}, fmt.Errorf("output %q must resolve directly inside the source package directory", outputFile)
	}
	if resolveErr != nil && !errors.Is(resolveErr, os.ErrNotExist) {
		return outputState{}, fmt.Errorf("resolve output %q: %w", outputFile, resolveErr)
	}
	state, err := readOutputState(outputPath)
	if err != nil {
		return outputState{}, fmt.Errorf("inspect output %q: %w", outputFile, err)
	}
	if !state.exists {
		return state, nil
	}
	file, parseErr := parser.ParseFile(token.NewFileSet(), outputPath, state.data, parser.ParseComments)
	if parseErr != nil || !isEventheaderGenerated(file) {
		return outputState{}, fmt.Errorf("refusing to overwrite %q: existing file is not generated by eventheader-gen", outputFile)
	}
	return state, nil
}

func readOutputState(outputPath string) (outputState, error) {
	file, err := os.Open(outputPath)
	if errors.Is(err, os.ErrNotExist) {
		return outputState{path: outputPath}, nil
	}
	if err != nil {
		return outputState{}, err
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil {
		return outputState{}, err
	}
	if !info.Mode().IsRegular() {
		return outputState{}, fmt.Errorf("output is not a regular file")
	}
	data, err := io.ReadAll(file)
	if err != nil {
		return outputState{}, err
	}
	return outputState{path: outputPath, exists: true, data: data, info: info}, nil
}

func (p *sourcePackage) checkSelectedGeneratedCollisions(typeNames []string) error {
	collisionFiles := make([]*ast.File, 0, len(p.files)+len(p.testFiles)+len(p.ignoredFiles))
	collisionFiles = append(collisionFiles, p.files...)
	collisionFiles = append(collisionFiles, p.testFiles...)
	collisionFiles = append(collisionFiles, p.ignoredFiles...)
	owners := make(map[string]string)
	for _, typeName := range typeNames {
		decl := p.types[typeName]
		if decl == nil {
			continue
		}
		for _, identifier := range generatedIdentifiers(typeName) {
			if previous, ok := owners[identifier]; ok {
				return p.errorf(decl.spec.Pos(),
					"generated identifier %s for event type %s collides with event type %s",
					identifier, typeName, previous)
			}
			owners[identifier] = typeName
		}
		eventConstraint := p.constraints[decl.file]
		for _, file := range collisionFiles {
			if !constraintsOverlap(eventConstraint, p.constraints[file], p.targets, p.knownOS, p.knownArch) {
				continue
			}
			for _, declaration := range file.Decls {
				switch value := declaration.(type) {
				case *ast.GenDecl:
					for _, spec := range value.Specs {
						switch item := spec.(type) {
						case *ast.TypeSpec:
							if generatedIdentifierOwner(typeName, item.Name.Name) {
								return p.errorf(item.Name.Pos(),
									"generated identifier %s collides with an existing declaration", item.Name.Name)
							}
						case *ast.ValueSpec:
							for _, name := range item.Names {
								if generatedIdentifierOwner(typeName, name.Name) {
									return p.errorf(name.Pos(),
										"generated identifier %s collides with an existing declaration", name.Name)
								}
							}
						}
					}
				case *ast.FuncDecl:
					if value.Recv == nil && generatedIdentifierOwner(typeName, value.Name.Name) {
						return p.errorf(value.Name.Pos(),
							"generated identifier %s collides with an existing declaration", value.Name.Name)
					}
				}
			}
		}
		writer := typeName + "Writer"
		for _, file := range collisionFiles {
			if !constraintsOverlap(eventConstraint, p.constraints[file], p.targets, p.knownOS, p.knownArch) {
				continue
			}
			for _, declaration := range file.Decls {
				function, ok := declaration.(*ast.FuncDecl)
				if !ok || function.Recv == nil ||
					receiverTypeName(function.Recv.List[0].Type) != writer {
					continue
				}
				switch function.Name.Name {
				case "Enabled", "Event", "Write", "bind":
					return p.errorf(function.Name.Pos(),
						"method %s.%s collides with an eventheader-gen generated method",
						writer, function.Name.Name)
				}
			}
		}
	}
	return nil
}

func (p *sourcePackage) checkPredeclaredShadows(typeNames []string) error {
	var eventConstraints []string
	for _, typeName := range typeNames {
		if decl := p.types[typeName]; decl != nil {
			eventConstraints = append(eventConstraints, p.constraints[decl.file])
		}
	}
	if len(eventConstraints) == 0 {
		return nil
	}
	packageFiles := make([]*ast.File, 0, len(p.files)+len(p.testFiles)+len(p.ignoredFiles))
	packageFiles = append(packageFiles, p.files...)
	packageFiles = append(packageFiles, p.testFiles...)
	packageFiles = append(packageFiles, p.ignoredFiles...)
	for _, file := range packageFiles {
		overlaps := false
		for _, eventConstraint := range eventConstraints {
			if constraintsOverlap(eventConstraint, p.constraints[file], p.targets, p.knownOS, p.knownArch) {
				overlaps = true
				break
			}
		}
		if !overlaps {
			continue
		}
		for _, declaration := range file.Decls {
			switch value := declaration.(type) {
			case *ast.GenDecl:
				for _, spec := range value.Specs {
					switch item := spec.(type) {
					case *ast.TypeSpec:
						if types.Universe.Lookup(item.Name.Name) != nil {
							return p.predeclaredShadowError(item.Name)
						}
					case *ast.ValueSpec:
						for _, name := range item.Names {
							if types.Universe.Lookup(name.Name) != nil {
								return p.predeclaredShadowError(name)
							}
						}
					}
				}
			case *ast.FuncDecl:
				if value.Recv == nil && types.Universe.Lookup(value.Name.Name) != nil {
					return p.predeclaredShadowError(value.Name)
				}
			}
		}
	}
	return nil
}

func (p *sourcePackage) predeclaredShadowError(name *ast.Ident) error {
	return p.errorf(name.Pos(),
		"package declaration %s shadows a predeclared Go identifier; generated code cannot safely reference the predeclared identifier",
		name.Name)
}

func generatedIdentifierOwner(typeName, identifier string) bool {
	for _, generated := range generatedIdentifiers(typeName) {
		if generated == identifier {
			return true
		}
	}
	return false
}

func (p *sourcePackage) addSyntheticDeclarations(selectedTypes []string) error {
	declared := make(map[string]bool)
	methods := make(map[string]map[string]bool)
	if p.outputPath == "" {
		for _, file := range p.typeFiles {
			for _, declaration := range file.Decls {
				switch value := declaration.(type) {
				case *ast.GenDecl:
					for _, spec := range value.Specs {
						switch item := spec.(type) {
						case *ast.TypeSpec:
							declared[item.Name.Name] = true
						case *ast.ValueSpec:
							for _, name := range item.Names {
								declared[name.Name] = true
							}
						}
					}
				case *ast.FuncDecl:
					if value.Recv == nil {
						declared[value.Name.Name] = true
						continue
					}
					receiver := receiverTypeName(value.Recv.List[0].Type)
					if receiver == "" {
						continue
					}
					if methods[receiver] == nil {
						methods[receiver] = make(map[string]bool)
					}
					methods[receiver][value.Name.Name] = true
				}
			}
		}
	}

	var declarations strings.Builder
	const eventheaderAlias = "eventheader_gen_synthetic_eventheader"
	const syncAlias = "eventheader_gen_synthetic_sync"
	for _, name := range selectedTypes {
		if p.types[name] == nil || p.types[name].spec.TypeParams != nil {
			continue
		}
		writer := name + "Writer"
		prefix := "eventheaderGen" + name
		if !declared[prefix+"SchemaOnce"] {
			fmt.Fprintf(&declarations, "var %sSchemaOnce %s.Once\n", prefix, syncAlias)
		}
		if !declared[prefix+"SchemaValue"] {
			fmt.Fprintf(&declarations, "var %sSchemaValue *%s.Schema\n", prefix, eventheaderAlias)
		}
		if !declared[prefix+"SchemaErr"] {
			fmt.Fprintf(&declarations, "var %sSchemaErr error\n", prefix)
		}
		if !declared[name+"Schema"] {
			fmt.Fprintf(&declarations, "func %sSchema() (*%s.Schema, error) { return nil, nil }\n", name, eventheaderAlias)
		}
		if !declared[writer] {
			fmt.Fprintf(&declarations, "type %s struct { event *%s.Event; binding %s.Binding }\n",
				writer, eventheaderAlias, eventheaderAlias)
		}
		if !declared["New"+writer] {
			fmt.Fprintf(&declarations, "func New%s(provider *%s.Provider, storage []byte) (*%s, error) { return nil, nil }\n",
				writer, eventheaderAlias, writer)
		}
		if !methods[writer]["Enabled"] {
			fmt.Fprintf(&declarations, "func (w *%s) Enabled() bool { return false }\n", writer)
		}
		if !methods[writer]["Event"] {
			fmt.Fprintf(&declarations, "func (w *%s) Event() *%s.Event { return nil }\n", writer, eventheaderAlias)
		}
		if !methods[writer]["Write"] {
			fmt.Fprintf(&declarations, "func (w *%s) Write(value *%s, activity, related *%s.ActivityID) error { return nil }\n",
				writer, name, eventheaderAlias)
		}
		if !methods[writer]["bind"] {
			fmt.Fprintf(&declarations, "func (w *%s) bind(value *%s) error { return nil }\n", writer, name)
		}
	}
	if declarations.Len() == 0 {
		return nil
	}
	source := fmt.Sprintf("package %s\nimport (\n%s %q\n%s %q\n)\nvar _ *%s.Event\nvar _ %s.Once\n%s",
		p.info.Name, eventheaderAlias, "github.com/cataggar/LinuxTracepoints-Go/eventheader",
		syncAlias, "sync", eventheaderAlias, syncAlias, declarations.String())
	file, err := parser.ParseFile(p.fset, filepath.Join(p.info.Dir, ".eventheader_gen_synthetic.go"), source, 0)
	if err != nil {
		return fmt.Errorf("parse synthetic generated declarations: %w", err)
	}
	p.typeFiles = append(p.typeFiles, file)
	return nil
}

func receiverTypeName(expr ast.Expr) string {
	if parenthesized, ok := expr.(*ast.ParenExpr); ok {
		return receiverTypeName(parenthesized.X)
	}
	if pointer, ok := expr.(*ast.StarExpr); ok {
		expr = pointer.X
	}
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name
	}
	return ""
}

func importsC(file *ast.File) bool {
	for _, imported := range file.Imports {
		if imported.Path.Value == `"C"` {
			return true
		}
	}
	return false
}

func (p *sourcePackage) typeCheck(tags string) (*types.Info, error) {
	information := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue),
		Defs:  make(map[*ast.Ident]types.Object),
		Uses:  make(map[*ast.Ident]types.Object),
	}
	lookup := func(importPath string) (io.ReadCloser, error) {
		args := []string{"list", "-export", "-f={{.Export}}"}
		if tags != "" {
			args = append(args, "-tags", tags)
		}
		args = append(args, importPath)
		command := exec.Command("go", args...)
		command.Dir = p.info.Dir
		output, err := command.Output()
		if err != nil {
			return nil, fmt.Errorf("resolve import %s: %w", importPath, err)
		}
		return os.Open(strings.TrimSpace(string(output)))
	}
	checker := types.Config{
		Importer:         importer.ForCompiler(p.fset, "gc", lookup),
		IgnoreFuncBodies: true,
		FakeImportC:      len(p.info.CgoFiles) != 0,
		Sizes:            types.SizesFor("gc", p.goarch),
	}
	var typeCheckErr error
	checker.Error = func(err error) {
		if typeCheckErr == nil {
			typeCheckErr = err
		}
	}
	_, err := checker.Check(p.info.ImportPath, p.fset, p.typeFiles, information)
	if typeCheckErr != nil {
		err = typeCheckErr
	}
	if err != nil {
		if typeError, ok := err.(types.Error); ok {
			return nil, &Diagnostic{
				Position: p.fset.PositionFor(typeError.Pos, true),
				Message:  typeError.Msg,
			}
		}
		return nil, err
	}
	return information, nil
}

func (p *sourcePackage) collectConstants(gen *ast.GenDecl, file *ast.File) {
	var previous []ast.Expr
	var previousType ast.Expr
	for _, item := range gen.Specs {
		spec := item.(*ast.ValueSpec)
		values := spec.Values
		if len(values) == 0 {
			values = previous
		} else {
			previous = values
			previousType = spec.Type
		}
		for i, name := range spec.Names {
			if len(values) == 0 {
				continue
			}
			expr := values[min(i, len(values)-1)]
			p.consts[name.Name] = constDecl{expr: expr, typ: previousType, file: file}
		}
	}
}

func knownTargetNames(dir string) (map[string]bool, map[string]bool, []buildTarget, error) {
	command := exec.Command("go", "tool", "dist", "list")
	command.Dir = dir
	output, err := command.Output()
	if err != nil {
		return nil, nil, nil, fmt.Errorf("list known Go targets: %w", err)
	}
	knownOS := make(map[string]bool)
	knownArch := make(map[string]bool)
	var targets []buildTarget
	for _, target := range strings.Fields(string(output)) {
		goos, goarch, ok := strings.Cut(target, "/")
		if !ok {
			continue
		}
		knownOS[goos] = true
		knownArch[goarch] = true
		targets = append(targets, buildTarget{goos: goos, goarch: goarch})
	}
	return knownOS, knownArch, targets, nil
}

func canonicalBuildConstraint(file *ast.File, filename string, knownOS, knownArch map[string]bool) (string, error) {
	var expressions []constraint.Expr
	for _, group := range file.Comments {
		if group.Pos() > file.Package {
			break
		}
		for _, comment := range group.List {
			text := strings.TrimSpace(comment.Text)
			if !constraint.IsGoBuild(text) && !constraint.IsPlusBuild(text) {
				continue
			}
			parsed, err := constraint.Parse(text)
			if err != nil {
				return "", fmt.Errorf("invalid build constraint: %w", err)
			}
			if constraint.IsGoBuild(text) {
				expressions = append(expressions, parsed)
				goto explicitDone
			}
			expressions = append(expressions, parsed)
		}
	}
explicitDone:
	expressions = append(expressions, filenameBuildConstraints(filename, knownOS, knownArch)...)
	return combineBuildConstraints(expressions), nil
}

func combineBuildConstraints(expressions []constraint.Expr) string {
	if len(expressions) == 0 {
		return ""
	}
	terms := make(map[string]constraint.Expr)
	var collect func(constraint.Expr)
	collect = func(expression constraint.Expr) {
		if and, ok := expression.(*constraint.AndExpr); ok {
			collect(and.X)
			collect(and.Y)
			return
		}
		terms[expression.String()] = expression
	}
	for _, expression := range expressions {
		collect(expression)
	}
	names := make([]string, 0, len(terms))
	for name := range terms {
		names = append(names, name)
	}
	sort.Strings(names)
	result := terms[names[0]]
	for _, name := range names[1:] {
		result = &constraint.AndExpr{X: result, Y: terms[name]}
	}
	return result.String()
}

func constraintDescription(value string) string {
	if value == "" {
		return "unconstrained"
	}
	return value
}

func parseBuildConstraint(value string) constraint.Expr {
	if value == "" {
		return nil
	}
	expression, err := constraint.Parse("//go:build " + value)
	if err != nil {
		panic("canonical build constraint did not parse: " + err.Error())
	}
	return expression
}

func constraintTags(expression constraint.Expr, tags map[string]bool) {
	switch value := expression.(type) {
	case *constraint.TagExpr:
		tags[value.Tag] = true
	case *constraint.NotExpr:
		constraintTags(value.X, tags)
	case *constraint.AndExpr:
		constraintTags(value.X, tags)
		constraintTags(value.Y, tags)
	case *constraint.OrExpr:
		constraintTags(value.X, tags)
		constraintTags(value.Y, tags)
	}
}

func constraintImplies(
	left, right string,
	targets []buildTarget,
	knownOS, knownArch map[string]bool,
) bool {
	if right == "" || left == right {
		return true
	}
	leftExpression := parseBuildConstraint(left)
	rightExpression := parseBuildConstraint(right)
	found, complete := evaluateValidAssignments(
		[]constraint.Expr{leftExpression, rightExpression},
		targets, knownOS, knownArch, 20,
		func(matches []bool) bool {
			return matches[0] && !matches[1]
		},
	)
	if !complete {
		return false
	}
	return !found
}

func constraintsEquivalent(
	left, right string,
	targets []buildTarget,
	knownOS, knownArch map[string]bool,
) bool {
	return constraintImplies(left, right, targets, knownOS, knownArch) &&
		constraintImplies(right, left, targets, knownOS, knownArch)
}

func constraintsOverlap(left, right string, targets []buildTarget, knownOS, knownArch map[string]bool) bool {
	if left == "" && right == "" {
		return true
	}
	leftExpression := parseBuildConstraint(left)
	rightExpression := parseBuildConstraint(right)
	found, complete := evaluateValidAssignments(
		[]constraint.Expr{leftExpression, rightExpression},
		targets, knownOS, knownArch, 12,
		func(matches []bool) bool { return matches[0] && matches[1] },
	)
	return found || !complete
}

func evaluateValidAssignments(
	expressions []constraint.Expr,
	targets []buildTarget,
	knownOS, knownArch map[string]bool,
	maxCustomTags int,
	accept func([]bool) bool,
) (found, complete bool) {
	tagSet := make(map[string]bool)
	for _, expression := range expressions {
		if expression != nil {
			constraintTags(expression, tagSet)
		}
	}
	var custom []string
	for tag := range tagSet {
		_, knownFeature, _ := architectureFeatureTag(tag, knownArch)
		if !knownOS[tag] && !knownArch[tag] && tag != "unix" && !knownFeature {
			custom = append(custom, tag)
		}
	}
	sort.Strings(custom)
	if len(custom) > maxCustomTags || len(targets) == 0 {
		return false, false
	}
	values := make(map[string]bool, len(custom))
	for _, target := range targets {
		for _, features := range architectureFeatureProfiles(target.goarch) {
			var search func(int) bool
			search = func(index int) bool {
				if index != len(custom) {
					values[custom[index]] = false
					if search(index + 1) {
						return true
					}
					values[custom[index]] = true
					return search(index + 1)
				}
				evaluate := func(tag string) bool {
					if knownOS[tag] || tag == "unix" {
						return targetMatchesOSBuildTag(target.goos, tag)
					}
					if knownArch[tag] {
						return target.goarch == tag
					}
					if featureArch, known, feature := architectureFeatureTag(tag, knownArch); feature {
						if featureArch != target.goarch {
							return false
						}
						if known {
							return features[tag]
						}
					}
					return values[tag]
				}
				matches := make([]bool, len(expressions))
				for i, expression := range expressions {
					matches[i] = expression == nil || expression.Eval(evaluate)
				}
				return accept(matches)
			}
			if search(0) {
				return true, true
			}
		}
	}
	return false, true
}

func architectureFeatureTag(tag string, knownArch map[string]bool) (arch string, known, feature bool) {
	arch, _, feature = strings.Cut(tag, ".")
	if !feature || !knownArch[arch] {
		return "", false, false
	}
	for _, profile := range architectureFeatureProfiles(arch) {
		if _, known = profile[tag]; known {
			break
		}
	}
	return arch, known, true
}

func architectureFeatureProfiles(arch string) []map[string]bool {
	levels := func(names ...string) []map[string]bool {
		profiles := make([]map[string]bool, len(names))
		enabled := make(map[string]bool, len(names))
		for i, name := range names {
			enabled[arch+"."+name] = true
			profiles[i] = mapsClone(enabled)
		}
		return profiles
	}
	exclusive := func(names ...string) []map[string]bool {
		profiles := make([]map[string]bool, len(names))
		for i, name := range names {
			profiles[i] = map[string]bool{arch + "." + name: true}
		}
		return profiles
	}

	switch arch {
	case "386":
		return exclusive("387", "sse2", "softfloat")
	case "amd64":
		return levels("v1", "v2", "v3", "v4")
	case "arm":
		return levels("5", "6", "7")
	case "arm64":
		var profiles []map[string]bool
		for minor := range 10 {
			profiles = append(profiles, arm64FeatureProfile(8, minor))
		}
		for minor := range 6 {
			profiles = append(profiles, arm64FeatureProfile(9, minor))
		}
		return profiles
	case "mips", "mipsle", "mips64", "mips64le":
		return exclusive("hardfloat", "softfloat")
	case "ppc64", "ppc64le":
		return levels("power8", "power9", "power10")
	case "riscv64":
		return levels("rva20u64", "rva22u64", "rva23u64")
	case "wasm":
		return []map[string]bool{
			nil,
			{"wasm.satconv": true},
			{"wasm.signext": true},
			{"wasm.satconv": true, "wasm.signext": true},
		}
	default:
		return []map[string]bool{nil}
	}
}

func arm64FeatureProfile(major, minor int) map[string]bool {
	profile := make(map[string]bool)
	for i := 0; i <= minor; i++ {
		profile[fmt.Sprintf("arm64.v%d.%d", major, i)] = true
	}
	if major == 9 {
		for i := 0; i <= minor+5 && i <= 9; i++ {
			profile[fmt.Sprintf("arm64.v8.%d", i)] = true
		}
	}
	return profile
}

func mapsClone(source map[string]bool) map[string]bool {
	clone := make(map[string]bool, len(source))
	for key, value := range source {
		clone[key] = value
	}
	return clone
}

func targetMatchesOSBuildTag(goos, tag string) bool {
	if goos == tag {
		return true
	}
	switch tag {
	case "linux":
		return goos == "android"
	case "solaris":
		return goos == "illumos"
	case "darwin":
		return goos == "ios"
	case "unix":
		switch goos {
		case "aix", "android", "darwin", "dragonfly", "freebsd", "hurd", "illumos",
			"ios", "linux", "netbsd", "openbsd", "solaris":
			return true
		}
	}
	return false
}

func filenameBuildConstraints(filename string, knownOS, knownArch map[string]bool) []constraint.Expr {
	name := strings.TrimSuffix(filepath.Base(filename), ".go")
	name = strings.TrimSuffix(name, "_test")
	parts := strings.Split(name, "_")
	if len(parts) < 2 {
		return nil
	}
	last := parts[len(parts)-1]
	if knownArch[last] {
		result := []constraint.Expr{&constraint.TagExpr{Tag: last}}
		if len(parts) >= 3 {
			previous := parts[len(parts)-2]
			if knownOS[previous] {
				result = append(result, &constraint.TagExpr{Tag: previous})
			}
		}
		return result
	}
	if knownOS[last] {
		return []constraint.Expr{&constraint.TagExpr{Tag: last}}
	}
	return nil
}

func (p *sourcePackage) annotatedTypes() ([]string, error) {
	var result []string
	for _, file := range p.files {
		for _, declaration := range file.Decls {
			gen, ok := declaration.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, item := range gen.Specs {
				spec := item.(*ast.TypeSpec)
				decl := p.types[spec.Name.Name]
				directive, _, err := p.findDirective(decl)
				if err != nil {
					return nil, err
				}
				if directive != "" {
					result = append(result, spec.Name.Name)
				}
			}
		}
	}
	return result, nil
}

func (p *sourcePackage) analyzeEvent(name string) (event, error) {
	decl := p.types[name]
	if decl == nil {
		return event{}, fmt.Errorf("type %q was not found in package %s", name, p.info.Name)
	}
	if decl.spec.TypeParams != nil {
		return event{}, p.errorf(decl.spec.TypeParams.Pos(), "event type %s must not be generic", name)
	}
	for _, generatedName := range []string{
		name + "Schema", name + "Writer", "New" + name + "Writer",
		"eventheaderGen" + name + "SchemaOnce",
		"eventheaderGen" + name + "SchemaValue",
		"eventheaderGen" + name + "SchemaErr",
	} {
		if position := p.decls[generatedName]; position.IsValid() {
			return event{}, p.errorf(position, "generated identifier %s collides with an existing declaration", generatedName)
		}
	}
	node, ok := decl.spec.Type.(*ast.StructType)
	if !ok {
		return event{}, p.errorf(decl.spec.Pos(), "event type %s must be a struct", name)
	}
	directive, pos, err := p.findDirective(decl)
	if err != nil {
		return event{}, err
	}
	if directive == "" {
		return event{}, p.errorf(decl.spec.Pos(), "type %s has no //eventheader:event directive", name)
	}
	options, err := p.parseEventOptions(directive, pos, name)
	if err != nil {
		return event{}, err
	}
	p.analysisConstraint = p.constraints[decl.file]
	defer func() { p.analysisConstraint = "" }()
	fields, err := p.analyzeStruct(node, decl.file, name, 0, map[string]bool{name: true})
	if err != nil {
		return event{}, err
	}
	scratch := 0
	assignScratch(fields, &scratch)
	result := event{
		TypeName: name, Options: options, Fields: fields,
		Constraint: p.constraints[decl.file], Position: decl.spec.Pos(),
	}
	if err := validateEventModel(result); err != nil {
		return event{}, p.errorf(decl.spec.Pos(), "%s: %v", name, err)
	}
	return result, nil
}

func generatedIdentifiers(typeName string) []string {
	return []string{
		typeName + "Schema",
		typeName + "Writer",
		"New" + typeName + "Writer",
		"eventheaderGen" + typeName + "SchemaOnce",
		"eventheaderGen" + typeName + "SchemaValue",
		"eventheaderGen" + typeName + "SchemaErr",
	}
}

func (p *sourcePackage) checkGeneratedCollisions(events []event) error {
	owners := make(map[string]event)
	for _, ev := range events {
		for _, identifier := range generatedIdentifiers(ev.TypeName) {
			if previous, ok := owners[identifier]; ok {
				return p.errorf(ev.Position,
					"generated identifier %s for event type %s collides with event type %s",
					identifier, ev.TypeName, previous.TypeName)
			}
			owners[identifier] = ev
		}
	}
	return nil
}

func assignScratch(fields []field, next *int) {
	for i := range fields {
		if fields[i].Constructor == "StructField" {
			assignScratch(fields[i].Children, next)
			continue
		}
		if fields[i].Scratch == "needed" {
			*next++
			fields[i].Scratch = fmt.Sprintf("eventheaderGenScratch%d", *next)
		}
		if fields[i].ScratchBacking == "needed" {
			*next++
			fields[i].ScratchBacking = fmt.Sprintf("eventheaderGenScratch%d", *next)
		}
	}
}

func validateEventModel(value event) error {
	fields := make([]eventheader.FieldDefinition, len(value.Fields))
	for i := range value.Fields {
		fields[i] = runtimeDefinition(value.Fields[i])
	}
	_, err := eventheader.NewSchema(eventheader.SchemaOptions{
		Name: value.Options.Name, ID: value.Options.ID, Version: value.Options.Version,
		Tag: eventheader.EventTag(value.Options.Tag), Opcode: eventheader.Opcode(value.Options.Opcode),
	}, fields...)
	return err
}

func runtimeDefinition(value field) eventheader.FieldDefinition {
	options := []eventheader.FieldOptions(nil)
	if value.Format != "" || value.Tag != 0 {
		formats := map[string]eventheader.FieldFormat{
			"FormatDefault": eventheader.FormatDefault, "FormatUnsignedInt": eventheader.FormatUnsignedInt,
			"FormatSignedInt": eventheader.FormatSignedInt, "FormatHexInt": eventheader.FormatHexInt,
			"FormatErrno": eventheader.FormatErrno, "FormatPID": eventheader.FormatPID,
			"FormatTime": eventheader.FormatTime, "FormatBoolean": eventheader.FormatBoolean,
			"FormatFloat": eventheader.FormatFloat, "FormatHexBytes": eventheader.FormatHexBytes,
			"FormatString8": eventheader.FormatString8, "FormatStringUTF": eventheader.FormatStringUTF,
			"FormatStringUTFBOM": eventheader.FormatStringUTFBOM, "FormatStringXML": eventheader.FormatStringXML,
			"FormatStringJSON": eventheader.FormatStringJSON, "FormatUUID": eventheader.FormatUUID,
			"FormatPort": eventheader.FormatPort, "FormatIPAddress": eventheader.FormatIPAddress,
		}
		options = []eventheader.FieldOptions{{Format: formats[value.Format], Tag: eventheader.FieldTag(value.Tag)}}
	}
	if value.Constructor == "StructField" {
		children := make([]eventheader.FieldDefinition, len(value.Children))
		for i := range value.Children {
			children[i] = runtimeDefinition(value.Children[i])
		}
		return eventheader.StructField(value.WireName, children, options...)
	}
	constructors := map[string]func(string, ...eventheader.FieldOptions) eventheader.FieldDefinition{
		"Int8Field": eventheader.Int8Field, "Uint8Field": eventheader.Uint8Field,
		"Int16Field": eventheader.Int16Field, "Uint16Field": eventheader.Uint16Field,
		"Int32Field": eventheader.Int32Field, "Uint32Field": eventheader.Uint32Field,
		"Int64Field": eventheader.Int64Field, "Uint64Field": eventheader.Uint64Field,
		"BoolField": eventheader.BoolField, "Float32Field": eventheader.Float32Field,
		"Float64Field": eventheader.Float64Field, "UintptrField": eventheader.UintptrField,
		"UUIDField": eventheader.UUIDField, "IPv4Field": eventheader.IPv4Field,
		"IPv6Field": eventheader.IPv6Field, "PortField": eventheader.PortField,
		"StringField": eventheader.StringField, "UTF16Field": eventheader.UTF16Field,
		"BinaryField": eventheader.BinaryField,
	}
	result := constructors[value.Constructor](value.WireName, options...)
	switch value.Array {
	case "fixed":
		return eventheader.ArrayField(result, eventheader.ArrayFixed, value.Count)
	case "variable":
		return eventheader.ArrayField(result, eventheader.ArrayVariable)
	default:
		return result
	}
}

func (p *sourcePackage) findDirective(decl *typeDecl) (string, token.Pos, error) {
	var groups []*ast.CommentGroup
	if decl.spec.Doc != nil {
		groups = append(groups, decl.spec.Doc)
	}
	for _, d := range decl.file.Decls {
		gen, ok := d.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			if spec == decl.spec && gen.Doc != nil && gen.Doc != decl.spec.Doc {
				groups = append(groups, gen.Doc)
			}
		}
	}
	var found string
	var foundPos token.Pos
	for _, group := range groups {
		for _, comment := range group.List {
			const prefix = "//eventheader:event"
			if !strings.HasPrefix(comment.Text, prefix) {
				continue
			}
			if found != "" {
				return "", 0, p.errorf(comment.Pos(), "repeated //eventheader:event directive")
			}
			found = strings.TrimSpace(strings.TrimPrefix(comment.Text, prefix))
			if found == "" {
				found = " "
			}
			foundPos = comment.Pos()
		}
	}
	return found, foundPos, nil
}

func splitOptions(text string) ([]string, error) {
	var result []string
	for i := 0; i < len(text); {
		for i < len(text) && unicode.IsSpace(rune(text[i])) {
			i++
		}
		if i == len(text) {
			break
		}
		start := i
		quote := byte(0)
		escaped := false
		for i < len(text) {
			c := text[i]
			if quote != 0 {
				if escaped {
					escaped = false
				} else if c == '\\' {
					escaped = true
				} else if c == quote {
					quote = 0
				}
				i++
				continue
			}
			if c == '"' || c == '\'' {
				quote = c
				i++
				continue
			}
			if unicode.IsSpace(rune(c)) {
				break
			}
			i++
		}
		if quote != 0 {
			return nil, errors.New("unterminated quoted option")
		}
		result = append(result, text[start:i])
	}
	return result, nil
}

func optionValue(raw string) (string, error) {
	if len(raw) >= 2 && (raw[0] == '"' || raw[0] == '\'') {
		value, err := strconv.Unquote(raw)
		if err != nil {
			return "", err
		}
		return value, nil
	}
	return raw, nil
}

func (p *sourcePackage) parseEventOptions(text string, pos token.Pos, typeName string) (eventOptions, error) {
	result := eventOptions{Name: typeName}
	tokens, err := splitOptions(text)
	if err != nil {
		return result, p.errorf(pos, "%v", err)
	}
	seen := make(map[string]bool)
	for _, item := range tokens {
		key, raw, ok := strings.Cut(item, "=")
		if !ok || key == "" || raw == "" {
			return result, p.errorf(pos, "event option %q must be key=value", item)
		}
		if seen[key] {
			return result, p.errorf(pos, "repeated event option %q", key)
		}
		seen[key] = true
		value, err := optionValue(raw)
		if err != nil {
			return result, p.errorf(pos, "event option %s: %v", key, err)
		}
		switch key {
		case "syntax":
			n, parseErr := strconv.ParseUint(value, 0, 64)
			if parseErr != nil || n != 1 {
				return result, p.errorf(pos, "unsupported event directive syntax %q; want 1", value)
			}
		case "name":
			if len(raw) < 2 || raw[0] != '"' {
				return result, p.errorf(pos, "event name must be a quoted Go string")
			}
			result.Name = value
		case "level":
			level, ok := levelNames[value]
			if !ok {
				n, parseErr := strconv.ParseUint(value, 0, 8)
				if parseErr != nil || n < 1 || n > 5 {
					return result, p.errorf(pos, "level must be critical, error, warning, information, verbose, or 1..5")
				}
				level = uint8(n)
			}
			result.Level = level
		case "keyword":
			n, parseErr := strconv.ParseUint(value, 0, 64)
			if parseErr != nil {
				return result, p.errorf(pos, "keyword %q is not a uint64", value)
			}
			result.Keyword = n
		case "group":
			if len(raw) < 2 || raw[0] != '"' {
				return result, p.errorf(pos, "event group must be a quoted Go string")
			}
			result.Group = value
		case "id":
			n, parseErr := strconv.ParseUint(value, 0, 16)
			if parseErr != nil {
				return result, p.errorf(pos, "id %q is not in 0..65535", value)
			}
			result.ID = uint16(n)
		case "version":
			n, parseErr := strconv.ParseUint(value, 0, 8)
			if parseErr != nil {
				return result, p.errorf(pos, "version %q is not in 0..255", value)
			}
			result.Version = uint8(n)
		case "tag":
			n, parseErr := strconv.ParseUint(value, 0, 16)
			if parseErr != nil {
				return result, p.errorf(pos, "tag %q is not in 0..65535", value)
			}
			result.Tag = uint16(n)
		case "opcode":
			opcode, ok := opcodeNames[value]
			if !ok {
				n, parseErr := strconv.ParseUint(value, 0, 8)
				if parseErr != nil {
					return result, p.errorf(pos, "opcode %q is not a named opcode or uint8", value)
				}
				opcode = uint8(n)
			}
			result.Opcode = opcode
		default:
			return result, p.errorf(pos, "unknown event option %q", key)
		}
	}
	if err := validateMetadataName(result.Name); err != nil {
		return result, p.errorf(pos, "event name: %v", err)
	}
	if !seen["level"] {
		return result, p.errorf(pos, "event directive requires a level")
	}
	if err := validateGroup(result.Group); err != nil {
		return result, p.errorf(pos, "%v", err)
	}
	return result, nil
}

func (p *sourcePackage) analyzeStruct(node *ast.StructType, file *ast.File, path string, depth int, active map[string]bool) ([]field, error) {
	if depth > 8 {
		return nil, p.errorf(node.Pos(), "struct nesting exceeds 8 at %s", path)
	}
	var result []field
	wireNames := make(map[string]bool)
	for _, astField := range node.Fields.List {
		options, err := p.parseTag(astField)
		if err != nil {
			return nil, err
		}
		if options.skip {
			continue
		}
		goName := ""
		if len(astField.Names) == 1 {
			goName = astField.Names[0].Name
			if goName == "_" {
				return nil, p.errorf(astField.Names[0].Pos(),
					"blank field at %s must be explicitly skipped with eventheader:\"-\"", path)
			}
		} else if len(astField.Names) == 0 {
			switch embedded := astField.Type.(type) {
			case *ast.Ident:
				goName = embedded.Name
			case *ast.SelectorExpr:
				goName = embedded.Sel.Name
			default:
				return nil, p.errorf(astField.Pos(), "embedded field at %s has an unsupported type", path)
			}
		} else {
			return nil, p.errorf(astField.Pos(), "field at %s must declare exactly one value", path)
		}
		wireName := goName
		if options.name != "" {
			wireName = options.name
		}
		if err := validateMetadataName(wireName); err != nil {
			return nil, p.errorf(astField.Pos(), "field %s: %v", path+"."+goName, err)
		}
		if wireNames[wireName] {
			return nil, p.errorf(astField.Pos(), "struct %s repeats wire field name %q", path, wireName)
		}
		wireNames[wireName] = true
		f, err := p.analyzeType(astField.Type, file, options, path+"."+goName, depth, active)
		if err != nil {
			return nil, err
		}
		f.GoName, f.WireName, f.Path, f.Position = goName, wireName, path+"."+goName, astField.Pos()
		result = append(result, f)
	}
	if depth > 0 && len(result) > 127 {
		return nil, p.errorf(node.Pos(), "struct %s has %d encoded children; maximum is 127", path, len(result))
	}
	return result, nil
}

func (p *sourcePackage) parseTag(field *ast.Field) (tagOptions, error) {
	result := tagOptions{position: field.Pos()}
	if field.Tag == nil {
		return result, nil
	}
	result.position = field.Tag.Pos()
	literal, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return result, p.errorf(field.Tag.Pos(), "invalid struct tag: %v", err)
	}
	keys, err := structTagKeys(literal)
	if err != nil {
		return result, p.errorf(field.Tag.Pos(), "invalid struct tag: %v", err)
	}
	if keys["eventheader"] > 1 {
		return result, p.errorf(field.Tag.Pos(), "repeated eventheader struct-tag key")
	}
	value, ok := reflect.StructTag(literal).Lookup("eventheader")
	if !ok {
		return result, nil
	}

	parts := strings.Split(value, ",")
	if len(parts) > 0 {
		if parts[0] == "-" {
			if len(parts) != 1 {
				return result, p.errorf(field.Tag.Pos(), "eventheader skip tag cannot have other options")
			}
			result.skip = true
			return result, nil
		}
		if parts[0] != "" {
			result.name = parts[0]
		}
	}
	seen := make(map[string]bool)
	for _, option := range parts[1:] {
		if option == "" {
			return result, p.errorf(field.Tag.Pos(), "empty eventheader struct-tag option")
		}
		key, value, hasValue := strings.Cut(option, "=")
		if seen[key] {
			return result, p.errorf(field.Tag.Pos(), "repeated eventheader option %q", key)
		}
		seen[key] = true
		switch key {
		case "format":
			if !hasValue || value == "" {
				return result, p.errorf(field.Tag.Pos(), "format requires a value")
			}
			mapped, ok := formatNames[value]
			if !ok {
				return result, p.errorf(field.Tag.Pos(), "unknown format %q", value)
			}
			result.format = mapped
		case "encoding":
			if !hasValue || value == "" {
				return result, p.errorf(field.Tag.Pos(), "encoding requires a value")
			}
			switch value {
			case "u8", "binary", "utf16", "uuid", "ipv4", "ipv6", "port":
				result.encoding = value
			default:
				return result, p.errorf(field.Tag.Pos(), "unknown encoding %q", value)
			}
		case "tag":
			if !hasValue {
				return result, p.errorf(field.Tag.Pos(), "tag requires a value")
			}
			n, parseErr := strconv.ParseUint(value, 0, 16)
			if parseErr != nil {
				return result, p.errorf(field.Tag.Pos(), "tag %q is not in 0..65535", value)
			}
			result.tag, result.tagSet = uint16(n), true
		default:
			return result, p.errorf(field.Tag.Pos(), "unknown eventheader option %q", key)
		}
	}
	return result, nil
}

func structTagKeys(tag string) (map[string]int, error) {
	result := make(map[string]int)
	for tag != "" {
		for len(tag) > 0 && tag[0] == ' ' {
			tag = tag[1:]
		}
		if tag == "" {
			break
		}
		index := 0
		for index < len(tag) && tag[index] > ' ' && tag[index] != ':' &&
			tag[index] != '"' && tag[index] != 0x7f {
			index++
		}
		if index == 0 || index+1 >= len(tag) || tag[index] != ':' || tag[index+1] != '"' {
			return nil, errors.New("expected key:\"value\"")
		}
		key := tag[:index]
		index++
		start := index
		index++
		for index < len(tag) && tag[index] != '"' {
			if tag[index] == '\\' {
				index++
			}
			index++
		}
		if index >= len(tag) {
			return nil, errors.New("unterminated quoted value")
		}
		if _, err := strconv.Unquote(tag[start : index+1]); err != nil {
			return nil, err
		}
		result[key]++
		tag = tag[index+1:]
	}
	return result, nil
}

type resolved struct {
	expr      ast.Expr
	file      *ast.File
	named     string
	alias     bool
	importPkg string
}

func (p *sourcePackage) checkDependency(pos token.Pos, kind, name string, file *ast.File) error {
	dependencyConstraint := p.constraints[file]
	if dependencyConstraint == "" ||
		constraintsEquivalent(
			p.analysisConstraint, dependencyConstraint,
			p.targets, p.knownOS, p.knownArch,
		) {
		return nil
	}
	return p.errorf(pos,
		"%s %s has build constraint %q, which does not match event constraint %q; move it to an unconstrained file or an equivalently constrained file",
		kind, name, dependencyConstraint, constraintDescription(p.analysisConstraint))
}

func (p *sourcePackage) resolve(expr ast.Expr, file *ast.File, active map[string]bool) (resolved, error) {
	switch value := expr.(type) {
	case *ast.Ident:
		decl := p.types[value.Name]
		if decl == nil {
			return resolved{expr: expr, file: file}, nil
		}
		if err := p.checkDependency(value.Pos(), "type", value.Name, decl.file); err != nil {
			return resolved{}, err
		}
		if decl.spec.TypeParams != nil {
			return resolved{}, p.errorf(value.Pos(), "generic type %s is not supported", value.Name)
		}
		return resolved{expr: decl.spec.Type, file: decl.file, named: value.Name, alias: decl.spec.Assign.IsValid()}, nil
	case *ast.SelectorExpr:
		ident, ok := value.X.(*ast.Ident)
		if !ok {
			return resolved{}, p.errorf(value.Pos(), "unsupported qualified type")
		}
		object, ok := p.typeInfo.Uses[ident].(*types.PkgName)
		if !ok || object.Imported() == nil {
			return resolved{}, p.errorf(ident.Pos(), "%s is not an imported package qualifier", ident.Name)
		}
		path := object.Imported().Path()
		return resolved{expr: expr, file: file, named: value.Sel.Name, importPkg: path}, nil
	default:
		return resolved{expr: expr, file: file}, nil
	}
}

func (p *sourcePackage) resolveTransitive(expr ast.Expr, file *ast.File, active map[string]bool) (resolved, error) {
	result, err := p.resolve(expr, file, active)
	if err != nil {
		return resolved{}, err
	}
	seen := make(map[string]bool)
	for result.importPkg == "" {
		if _, ok := result.expr.(*ast.SelectorExpr); ok {
			return p.resolve(result.expr, result.file, active)
		}
		identifier, ok := result.expr.(*ast.Ident)
		if !ok || p.types[identifier.Name] == nil {
			break
		}
		if seen[identifier.Name] {
			return resolved{}, p.errorf(expr.Pos(), "recursive named type %s", identifier.Name)
		}
		seen[identifier.Name] = true
		result, err = p.resolve(result.expr, result.file, active)
		if err != nil {
			return resolved{}, err
		}
	}
	return result, nil
}

func (p *sourcePackage) analyzeType(expr ast.Expr, file *ast.File, options tagOptions, path string, depth int, active map[string]bool) (field, error) {
	resolvedType, err := p.resolve(expr, file, active)
	if err != nil {
		return field{}, err
	}
	hasDefinedWrapper := resolvedType.importPkg == "" && resolvedType.named != "" && !resolvedType.alias
	resolutionNames := make(map[string]bool)
	for resolvedType.importPkg == "" {
		ident, ok := resolvedType.expr.(*ast.Ident)
		if !ok || p.types[ident.Name] == nil {
			break
		}
		if resolutionNames[ident.Name] {
			return field{}, p.errorf(expr.Pos(), "field %s has a recursive named type", path)
		}
		resolutionNames[ident.Name] = true
		resolvedType, err = p.resolve(resolvedType.expr, resolvedType.file, active)
		if err != nil {
			return field{}, err
		}
		hasDefinedWrapper = hasDefinedWrapper ||
			resolvedType.importPkg == "" && resolvedType.named != "" && !resolvedType.alias
	}
	if resolvedType.importPkg == "" {
		if _, ok := resolvedType.expr.(*ast.SelectorExpr); ok {
			resolvedType, err = p.resolve(resolvedType.expr, resolvedType.file, active)
			if err != nil {
				return field{}, err
			}
		}
	}
	if resolvedType.importPkg != "" {
		if (resolvedType.importPkg == "net" && resolvedType.named == "IP") ||
			(resolvedType.importPkg == "net/netip" && resolvedType.named == "Addr") {
			if hasDefinedWrapper {
				return field{}, p.errorf(expr.Pos(), "field %s uses a defined wrapper around %s.%s; use a type alias", path, resolvedType.importPkg, resolvedType.named)
			}
			return p.analyzeIPType(expr, resolvedType, options, path)
		}
		if resolvedType.importPkg == "time" && resolvedType.named == "Duration" {
			return p.analyzePrimitive(expr, "int64", options, path)
		}
		if typ := p.typeInfo.TypeOf(expr); typ != nil {
			if _, ok := types.Unalias(typ).Underlying().(*types.Basic); ok {
				return field{}, p.errorf(expr.Pos(),
					"field %s uses imported named primitive %s.%s, whose target parity is not established",
					path, resolvedType.importPkg, resolvedType.named)
			}
		}
		return field{}, p.errorf(expr.Pos(), "field %s uses imported type %s.%s; imported structs are not supported", path, resolvedType.importPkg, resolvedType.named)
	}
	underlying := resolvedType.expr
	switch value := underlying.(type) {
	case *ast.StructType:
		if options.encoding != "" {
			return field{}, p.errorf(options.position, "field %s: encoding is incompatible with a struct", path)
		}
		if options.format != "" && options.format != "FormatDefault" {
			return field{}, p.errorf(options.position, "field %s: struct format must be default", path)
		}
		if resolvedType.named != "" {
			if active[resolvedType.named] {
				return field{}, p.errorf(expr.Pos(), "field %s recursively contains %s", path, resolvedType.named)
			}
			active[resolvedType.named] = true
			defer delete(active, resolvedType.named)
		}
		children, err := p.analyzeStruct(value, resolvedType.file, path, depth+1, active)
		if err != nil {
			return field{}, err
		}
		if len(children) == 0 {
			return field{}, p.errorf(expr.Pos(), "field %s is an empty struct", path)
		}
		return field{Constructor: "StructField", Children: children, Format: options.format, Tag: options.tag}, nil
	case *ast.StarExpr:
		return field{}, p.errorf(expr.Pos(), "field %s is a pointer; pointers are not supported", path)
	case *ast.InterfaceType, *ast.MapType, *ast.ChanType, *ast.FuncType:
		return field{}, p.errorf(expr.Pos(), "field %s has unsupported type %s", path, p.exprString(expr))
	case *ast.ArrayType:
		return p.analyzeArray(expr, value, resolvedType.file, options, path, depth, active)
	case *ast.Ident:
		return p.analyzePrimitive(expr, value.Name, options, path)
	default:
		return field{}, p.errorf(expr.Pos(), "field %s has unsupported type %s", path, p.exprString(expr))
	}
}

func (p *sourcePackage) analyzePrimitive(original ast.Expr, name string, options tagOptions, path string) (field, error) {
	mapping := map[string][3]string{
		"int8": {"Int8Field", "Int8", "int8"}, "uint8": {"Uint8Field", "Uint8", "uint8"},
		"byte": {"Uint8Field", "Uint8", "byte"}, "int16": {"Int16Field", "Int16", "int16"},
		"uint16": {"Uint16Field", "Uint16", "uint16"}, "int32": {"Int32Field", "Int32", "int32"},
		"rune": {"Int32Field", "Int32", "rune"}, "uint32": {"Uint32Field", "Uint32", "uint32"},
		"int64": {"Int64Field", "Int64", "int64"}, "uint64": {"Uint64Field", "Uint64", "uint64"},
		"bool": {"BoolField", "Bool", "bool"}, "float32": {"Float32Field", "Float32", "float32"},
		"float64": {"Float64Field", "Float64", "float64"}, "uintptr": {"UintptrField", "Uintptr", "uintptr"},
		"string": {"StringField", "String", "string"},
	}
	if name == "int" || name == "uint" {
		return field{}, p.errorf(original.Pos(), "field %s uses %s; use an explicitly sized integer", path, name)
	}
	item, ok := mapping[name]
	if !ok {
		return field{}, p.errorf(original.Pos(), "field %s has unknown type %s", path, name)
	}
	if options.encoding != "" {
		if options.encoding != "port" || name != "uint16" {
			return field{}, p.errorf(options.position, "field %s: encoding=%s is incompatible with %s", path, options.encoding, name)
		}
		item = [3]string{"PortField", "Port", "uint16"}
	}
	result := field{Constructor: item[0], Method: item[1], BaseType: item[2], Format: options.format, Tag: options.tag, OriginalType: original}
	if err := checkFormat(result, options, path); err != nil {
		return field{}, p.errorf(options.position, "%v", err)
	}
	return result, nil
}

func (p *sourcePackage) analyzeArray(original ast.Expr, array *ast.ArrayType, file *ast.File, options tagOptions, path string, depth int, active map[string]bool) (field, error) {
	if _, ok := array.Elt.(*ast.StarExpr); ok {
		return field{}, p.errorf(array.Elt.Pos(), "field %s contains pointers", path)
	}
	isSlice := array.Len == nil
	var fixedCount uint64
	if !isSlice {
		if err := p.checkConstantDependencies(array.Len, make(map[string]bool)); err != nil {
			return field{}, err
		}
		if !p.architectureIndependentIntegerConstant(array.Len, make(map[string]bool)) {
			return field{}, p.errorf(array.Len.Pos(),
				"field %s fixed array length is not provably architecture-independent; use an explicit fixed count or separate architecture-constrained source/output",
				path)
		}
		var ok bool
		fixedCount, ok = p.arrayLength(array.Len)
		if !ok {
			return field{}, p.errorf(array.Len.Pos(), "field %s fixed array count must be in 0..65535", path)
		}
	}
	// []byte is binary by default; []uint16 can be explicitly UTF-16.
	element, err := p.resolveTransitive(array.Elt, file, active)
	if err != nil {
		return field{}, err
	}
	if element.importPkg != "" &&
		!(element.importPkg == "time" && element.named == "Duration") {
		if typ := p.typeInfo.TypeOf(array.Elt); typ != nil {
			if _, ok := types.Unalias(typ).Underlying().(*types.Basic); ok {
				return field{}, p.errorf(array.Elt.Pos(),
					"field %s uses imported named primitive %s.%s, whose target parity is not established",
					path, element.importPkg, element.named)
			}
		}
	}
	elementIdent, primitive := element.expr.(*ast.Ident)
	elementName := ""
	if primitive {
		elementName = elementIdent.Name
	}
	elementIsByte := p.hasUnderlyingBasicType(array.Elt, types.Uint8)
	if !isSlice && elementIsByte && options.encoding == "binary" {
		if fixedCount > 65535 {
			return field{}, p.errorf(array.Len.Pos(), "field %s binary length must be in 0..65535", path)
		}
		result := field{Constructor: "BinaryField", Method: "Binary", BaseType: "[]byte", Format: options.format, Tag: options.tag, Semantic: "binary-fixed", OriginalType: original}
		if !p.canPassCollectionDirectly(original, "byte") {
			result.Scratch = "needed"
		}
		if err := checkFormat(result, options, path); err != nil {
			return field{}, p.errorf(options.position, "%v", err)
		}
		return result, nil
	}
	if isSlice && elementIsByte && options.encoding != "u8" {
		if options.encoding != "" && options.encoding != "binary" {
			return field{}, p.errorf(options.position, "field %s: encoding=%s is incompatible with []byte", path, options.encoding)
		}
		result := field{Constructor: "BinaryField", Method: "Binary", BaseType: "[]byte", Format: options.format, Tag: options.tag, Semantic: "binary", OriginalType: original}
		if !p.canPassCollectionDirectly(original, "byte") {
			result.Scratch = "needed"
		}
		if err := checkFormat(result, options, path); err != nil {
			return field{}, p.errorf(options.position, "%v", err)
		}
		return result, nil
	}
	if isSlice && elementName == "uint16" && options.encoding == "utf16" {
		result := field{Constructor: "UTF16Field", Method: "UTF16", BaseType: "[]uint16", Format: options.format, Tag: options.tag, Semantic: "utf16", OriginalType: original}
		if !p.canPassCollectionDirectly(original, "uint16") {
			result.Scratch = "needed"
		}
		if err := checkFormat(result, options, path); err != nil {
			return field{}, p.errorf(options.position, "%v", err)
		}
		return result, nil
	}
	if options.encoding == "uuid" || options.encoding == "ipv4" || options.encoding == "ipv6" {
		required := uint64(16)
		if options.encoding == "ipv4" {
			required = 4
		}
		count, ok := uint64(0), false
		if array.Len != nil {
			count, ok = fixedCount, true
		}
		if ok && count == required && elementIsByte {
			names := map[string][3]string{
				"uuid": {"UUIDField", "UUID", "[16]byte"}, "ipv4": {"IPv4Field", "IPv4", "[4]byte"},
				"ipv6": {"IPv6Field", "IPv6", "[16]byte"},
			}
			item := names[options.encoding]
			result := field{Constructor: item[0], Method: item[1], BaseType: item[2], Format: options.format, Tag: options.tag, Semantic: options.encoding, OriginalType: original}
			result.ElementWise = p.needsElementWiseFixedConversion(original, required)
			if err := checkFormat(result, options, path); err != nil {
				return field{}, p.errorf(options.position, "%v", err)
			}
			return result, nil
		}
	}
	elementOptions := options
	if options.encoding == "u8" && elementIsByte {
		elementOptions.encoding = ""
	}
	elementOptions.format = options.format
	elementOptions.tag = options.tag
	base, err := p.analyzeType(array.Elt, file, elementOptions, path+"[]", depth, active)
	if err != nil {
		return field{}, err
	}
	if base.Constructor == "StructField" {
		return field{}, p.errorf(original.Pos(), "field %s is an array of structs; struct arrays are not supported", path)
	}
	if base.NetType != "" {
		return field{}, p.errorf(original.Pos(), "field %s is a collection of %s addresses; address collections require fixed byte-array elements", path, base.NetType)
	}
	if base.Array != "" {
		return field{}, p.errorf(original.Pos(), "field %s is a nested array; only arrays of scalar values are supported", path)
	}
	base.Array = "variable"
	base.DirectArray = p.canPassArrayDirectly(original, base)
	if !base.DirectArray {
		if base.Scratch != "" && strings.HasPrefix(base.BaseType, "[]") {
			base.ScratchBacking = "needed"
		}
		base.Scratch = "needed"
	}
	if !isSlice {
		if fixedCount == 0 || fixedCount > 65535 {
			return field{}, p.errorf(array.Len.Pos(), "field %s fixed array count must be in 1..65535", path)
		}
		base.Array, base.Count = "fixed", uint16(fixedCount)
		base.FixedOuter = true
	}
	base.Method += "Array"
	base.OriginalType = original
	return base, nil
}

func (p *sourcePackage) hasUnderlyingBasicType(expr ast.Expr, kind types.BasicKind) bool {
	if p.typeInfo == nil {
		return false
	}
	typ := p.typeInfo.TypeOf(expr)
	if typ == nil {
		return false
	}
	basic, ok := types.Unalias(typ).Underlying().(*types.Basic)
	return ok && basic.Kind() == kind
}

func (p *sourcePackage) canPassArrayDirectly(original ast.Expr, value field) bool {
	if value.Semantic == "binary-fixed" || p.typeInfo == nil {
		return false
	}
	typ := p.typeInfo.TypeOf(original)
	if typ == nil {
		return false
	}
	var element types.Type
	switch underlying := typ.Underlying().(type) {
	case *types.Array:
		element = underlying.Elem()
	case *types.Slice:
		element = underlying.Elem()
	default:
		return false
	}
	basic := map[string]types.Type{
		"int8": types.Typ[types.Int8], "uint8": types.Typ[types.Uint8],
		"byte": types.Typ[types.Uint8], "int16": types.Typ[types.Int16],
		"uint16": types.Typ[types.Uint16], "int32": types.Typ[types.Int32],
		"rune": types.Typ[types.Int32], "uint32": types.Typ[types.Uint32],
		"int64": types.Typ[types.Int64], "uint64": types.Typ[types.Uint64],
		"bool": types.Typ[types.Bool], "float32": types.Typ[types.Float32],
		"float64": types.Typ[types.Float64], "uintptr": types.Typ[types.Uintptr],
		"string": types.Typ[types.String],
	}
	expected := basic[value.BaseType]
	switch value.BaseType {
	case "[4]byte":
		expected = types.NewArray(types.Typ[types.Uint8], 4)
	case "[16]byte":
		expected = types.NewArray(types.Typ[types.Uint8], 16)
	case "[]byte":
		expected = types.NewSlice(types.Typ[types.Uint8])
	case "[]uint16":
		expected = types.NewSlice(types.Typ[types.Uint16])
	}
	return expected != nil && types.AssignableTo(types.NewSlice(element), types.NewSlice(expected))
}

func (p *sourcePackage) canPassCollectionDirectly(original ast.Expr, baseType string) bool {
	return p.canPassArrayDirectly(original, field{BaseType: baseType})
}

func (p *sourcePackage) needsElementWiseFixedConversion(original ast.Expr, count uint64) bool {
	if p.typeInfo == nil {
		return true
	}
	typ := p.typeInfo.TypeOf(original)
	if typ == nil {
		return true
	}
	target := types.NewArray(types.Typ[types.Uint8], int64(count))
	return !types.ConvertibleTo(typ, target)
}

func (p *sourcePackage) checkConstantDependencies(expr ast.Expr, active map[string]bool) error {
	var result error
	ast.Inspect(expr, func(node ast.Node) bool {
		if result != nil {
			return false
		}
		identifier, ok := node.(*ast.Ident)
		if !ok {
			return true
		}
		declaration, ok := p.consts[identifier.Name]
		if !ok {
			typeDeclaration := p.types[identifier.Name]
			object, isType := p.typeInfo.Uses[identifier].(*types.TypeName)
			if typeDeclaration != nil && isType && object.Pkg() != nil &&
				object.Pkg().Path() == p.info.ImportPath {
				result = p.checkDependency(identifier.Pos(), "type", identifier.Name, typeDeclaration.file)
			}
			return false
		}
		if active[identifier.Name] {
			return false
		}
		if err := p.checkDependency(identifier.Pos(), "constant", identifier.Name, declaration.file); err != nil {
			result = err
			return false
		}
		active[identifier.Name] = true
		if declaration.typ != nil {
			result = p.checkConstantDependencies(declaration.typ, active)
		}
		if result != nil {
			delete(active, identifier.Name)
			return false
		}
		result = p.checkConstantDependencies(declaration.expr, active)
		delete(active, identifier.Name)
		return false
	})
	return result
}

func (p *sourcePackage) architectureIndependentIntegerConstant(expr ast.Expr, active map[string]bool) bool {
	switch value := expr.(type) {
	case *ast.BasicLit:
		return value.Kind == token.INT
	case *ast.ParenExpr:
		return p.architectureIndependentIntegerConstant(value.X, active)
	case *ast.Ident:
		if value.Name == "iota" {
			return true
		}
		definition, ok := p.consts[value.Name]
		if !ok || active[value.Name] {
			return false
		}
		object, ok := p.typeInfo.Uses[value].(*types.Const)
		if !ok || architectureDependentIntegerType(object.Type()) {
			return false
		}
		active[value.Name] = true
		defer delete(active, value.Name)
		return p.architectureIndependentIntegerConstant(definition.expr, active)
	case *ast.UnaryExpr:
		switch value.Op {
		case token.ADD, token.SUB, token.XOR:
			return p.architectureIndependentIntegerConstant(value.X, active)
		}
	case *ast.BinaryExpr:
		switch value.Op {
		case token.ADD, token.SUB, token.MUL, token.QUO, token.REM,
			token.SHL, token.SHR, token.AND, token.OR, token.XOR, token.AND_NOT:
			return p.architectureIndependentIntegerConstant(value.X, active) &&
				p.architectureIndependentIntegerConstant(value.Y, active)
		}
	}
	return false
}

func architectureDependentIntegerType(typ types.Type) bool {
	basic, ok := types.Unalias(typ).Underlying().(*types.Basic)
	if !ok {
		return false
	}
	return basic.Kind() == types.Int || basic.Kind() == types.Uint || basic.Kind() == types.Uintptr
}

func (p *sourcePackage) arrayLength(expr ast.Expr) (uint64, bool) {
	if p.typeInfo == nil {
		return 0, false
	}
	value := p.typeInfo.Types[expr].Value
	if value == nil {
		return 0, false
	}
	result, exact := constant.Uint64Val(value)
	return result, exact
}

func (p *sourcePackage) analyzeIPType(original ast.Expr, resolvedType resolved, options tagOptions, path string) (field, error) {
	if options.encoding != "ipv4" && options.encoding != "ipv6" {
		return field{}, p.errorf(options.position, "field %s uses %s.%s; specify encoding=ipv4 or encoding=ipv6", path, resolvedType.importPkg, resolvedType.named)
	}
	item := [3]string{"IPv4Field", "IPv4", "[4]byte"}
	if options.encoding == "ipv6" {
		item = [3]string{"IPv6Field", "IPv6", "[16]byte"}
	}
	netType := "netip"
	if resolvedType.importPkg == "net" {
		netType = "net"
	}
	result := field{
		Constructor: item[0], Method: item[1], BaseType: item[2],
		Format: options.format, Tag: options.tag, Semantic: options.encoding,
		NetType: netType, OriginalType: original,
	}
	if err := checkFormat(result, options, path); err != nil {
		return field{}, p.errorf(options.position, "%v", err)
	}
	return result, nil
}

func checkFormat(value field, options tagOptions, path string) error {
	if options.format == "" || options.format == "FormatDefault" {
		return nil
	}
	allowed := map[string]map[string]bool{
		"Bool": {"FormatBoolean": true}, "Float32": {"FormatFloat": true}, "Float64": {"FormatFloat": true},
		"String": {"FormatString8": true, "FormatStringUTF": true, "FormatStringUTFBOM": true, "FormatStringXML": true, "FormatStringJSON": true},
		"Binary": {"FormatHexBytes": true}, "UTF16": {"FormatStringUTF": true, "FormatStringUTFBOM": true, "FormatStringXML": true, "FormatStringJSON": true},
		"UUID": {"FormatUUID": true}, "IPv4": {"FormatIPAddress": true}, "IPv6": {"FormatIPAddress": true},
		"Port": {"FormatPort": true},
	}
	if strings.HasPrefix(value.Method, "Int") || strings.HasPrefix(value.Method, "Uint") {
		switch options.format {
		case "FormatUnsignedInt", "FormatSignedInt", "FormatHexInt", "FormatErrno", "FormatPID", "FormatTime":
			return nil
		}
	}
	if allowed[strings.TrimSuffix(value.Method, "Array")][options.format] {
		return nil
	}
	return fmt.Errorf("field %s: format is incompatible with its encoding", path)
}

func validateMetadataName(name string) error {
	if name == "" {
		return errors.New("name is empty")
	}
	if !utf8.ValidString(name) {
		return errors.New("name is not valid UTF-8")
	}
	if strings.IndexAny(name, "\x00;") >= 0 {
		return errors.New("name contains NUL or semicolon")
	}
	return nil
}

func validateGroup(group string) error {
	for i := range len(group) {
		if (group[i] < 'a' || group[i] > 'z') && (group[i] < '0' || group[i] > '9') {
			return fmt.Errorf("group %q must contain only lowercase ASCII letters and digits", group)
		}
	}
	return nil
}

func (p *sourcePackage) exprString(expr ast.Expr) string {
	var out strings.Builder
	_ = printer.Fprint(&out, p.fset, expr)
	return out.String()
}

func (p *sourcePackage) errorf(pos token.Pos, format string, args ...any) error {
	return &Diagnostic{Position: p.fset.PositionFor(pos, true), Message: fmt.Sprintf(format, args...)}
}

func render(packageName, buildConstraint string, events []event) ([]byte, error) {
	var out strings.Builder
	if buildConstraint != "" {
		fmt.Fprintf(&out, "//go:build %s\n\n", buildConstraint)
	}
	out.WriteString(GeneratedMarker + "\n")
	out.WriteString(generatedSyntax + "\n\n")
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	out.WriteString("import (\n")
	out.WriteString("\teventheader_gen_fmt \"fmt\"\n")
	out.WriteString("\teventheader_gen_sync \"sync\"\n")
	out.WriteString("\n\teventheader_gen_eventheader \"github.com/cataggar/LinuxTracepoints-Go/eventheader\"\n")
	out.WriteString("\teventheader_gen_userevents \"github.com/cataggar/LinuxTracepoints-Go/userevents\"\n")
	out.WriteString(")\n\n")
	for _, ev := range events {
		renderEvent(&out, ev)
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, out.String())
	}
	return formatted, nil
}

func renderEvent(out *strings.Builder, ev event) {
	prefix := "eventheaderGen" + ev.TypeName
	fmt.Fprintf(out, "var (\n\t%sSchemaOnce eventheader_gen_sync.Once\n", prefix)
	fmt.Fprintf(out, "\t%sSchemaValue *eventheader_gen_eventheader.Schema\n", prefix)
	fmt.Fprintf(out, "\t%sSchemaErr error\n)\n\n", prefix)
	fmt.Fprintf(out, "// %sSchema returns the immutable schema for %s.\n", ev.TypeName, ev.TypeName)
	fmt.Fprintf(out, "func %sSchema() (*eventheader_gen_eventheader.Schema, error) {\n", ev.TypeName)
	fmt.Fprintf(out, "\t%sSchemaOnce.Do(func() {\n", prefix)
	fmt.Fprintf(out, "\t\t%sSchemaValue, %sSchemaErr = eventheader_gen_eventheader.NewSchema(\n", prefix, prefix)
	fmt.Fprintf(out, "\t\t\teventheader_gen_eventheader.SchemaOptions{Name: %q, ID: %d, Version: %d, Tag: %d, Opcode: %d},\n",
		ev.Options.Name, ev.Options.ID, ev.Options.Version, ev.Options.Tag, ev.Options.Opcode)
	for _, f := range ev.Fields {
		fmt.Fprintf(out, "\t\t\t%s,\n", schemaExpression(f))
	}
	out.WriteString("\t\t)\n\t})\n")
	fmt.Fprintf(out, "\treturn %sSchemaValue, %sSchemaErr\n}\n\n", prefix, prefix)
	fmt.Fprintf(out, "// %sWriter is goroutine-local reusable state for %s.\n", ev.TypeName, ev.TypeName)
	fmt.Fprintf(out, "type %sWriter struct {\n\tevent *eventheader_gen_eventheader.Event\n\tbinding eventheader_gen_eventheader.Binding\n", ev.TypeName)
	renderScratchFields(out, ev.Fields)
	out.WriteString("}\n\n")
	fmt.Fprintf(out, "// New%sWriter binds %s to provider. A writer must be used by only one goroutine.\n", ev.TypeName, ev.TypeName)
	fmt.Fprintf(out, "func New%sWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*%sWriter, error) {\n", ev.TypeName, ev.TypeName)
	fmt.Fprintf(out, "\tschema, err := %sSchema()\n\tif err != nil { return nil, err }\n", ev.TypeName)
	fmt.Fprintf(out, "\tset, err := provider.EventSet(%d, %#x, %q)\n\tif err != nil { return nil, err }\n", ev.Options.Level, ev.Options.Keyword, ev.Options.Group)
	out.WriteString("\tevent, err := eventheader_gen_eventheader.NewEvent(set, schema)\n\tif err != nil { return nil, err }\n")
	fmt.Fprintf(out, "\treturn &%sWriter{event: event, binding: event.Bind(storage)}, nil\n}\n\n", ev.TypeName)
	fmt.Fprintf(out, "// Enabled reports whether the %s event is enabled.\n", ev.Options.Name)
	fmt.Fprintf(out, "func (w *%sWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }\n\n", ev.TypeName)
	fmt.Fprintf(out, "// Event returns the reusable runtime event.\nfunc (w *%sWriter) Event() *eventheader_gen_eventheader.Event {\n", ev.TypeName)
	out.WriteString("\tif w == nil { return nil }\n\treturn w.event\n}\n\n")
	fmt.Fprintf(out, "// Write encodes value and emits it with optional activity correlation IDs.\nfunc (w *%sWriter) Write(value *%s, activity, related *eventheader_gen_eventheader.ActivityID) error {\n", ev.TypeName, ev.TypeName)
	out.WriteString("\tif w == nil || w.event == nil { return eventheader_gen_userevents.ErrClosed }\n")
	out.WriteString("\tif !w.event.Enabled() { return w.event.Write(nil, nil, nil) }\n")
	out.WriteString("\tif err := w.bind(value); err != nil { return err }\n")
	out.WriteString("\treturn w.event.Write(&w.binding, activity, related)\n}\n\n")
	fmt.Fprintf(out, "func (w *%sWriter) bind(value *%s) error {\n", ev.TypeName, ev.TypeName)
	out.WriteString("\tif value == nil { return eventheader_gen_fmt.Errorf(\"event value: %w\", eventheader_gen_eventheader.ErrInvalidValue) }\n")
	temp := 0
	renderScratchPreflight(out, ev.Fields, "value", "\t", &temp)
	out.WriteString("\tw.binding.Reset()\n")
	for _, f := range ev.Fields {
		renderBinding(out, f, "value."+f.GoName, "\t", &temp)
	}
	out.WriteString("\treturn nil\n}\n\n")
}

func renderScratchPreflight(out *strings.Builder, fields []field, expression, indent string, temp *int) {
	for _, f := range fields {
		fieldExpression := expression + "." + f.GoName
		if f.Constructor == "StructField" {
			renderScratchPreflight(out, f.Children, fieldExpression, indent, temp)
			continue
		}
		if f.Scratch != "" {
			renderScratchValidation(out, f, fieldExpression, indent, temp)
		}
	}
}

func renderScratchFields(out *strings.Builder, fields []field) {
	for _, f := range fields {
		if f.Constructor == "StructField" {
			renderScratchFields(out, f.Children)
			continue
		}
		if f.Scratch == "" {
			continue
		}
		scratchType := f.BaseType
		if f.Array != "" {
			scratchType = "[]" + scratchType
		}
		fmt.Fprintf(out, "\t%s %s\n", f.Scratch, scratchType)
		if f.ScratchBacking != "" {
			fmt.Fprintf(out, "\t%s %s\n", f.ScratchBacking, f.BaseType)
		}
	}
}

func fieldOptions(f field) string {
	if f.Format == "" && f.Tag == 0 {
		return ""
	}
	formatName := f.Format
	if formatName == "" {
		formatName = "FormatDefault"
	}
	return fmt.Sprintf(", eventheader_gen_eventheader.FieldOptions{Format: eventheader_gen_eventheader.%s, Tag: %d}", formatName, f.Tag)
}

func schemaExpression(f field) string {
	if f.Constructor == "StructField" {
		children := make([]string, len(f.Children))
		for i := range f.Children {
			children[i] = schemaExpression(f.Children[i])
		}
		return fmt.Sprintf("eventheader_gen_eventheader.StructField(%q, []eventheader_gen_eventheader.FieldDefinition{%s}%s)",
			f.WireName, strings.Join(children, ", "), fieldOptions(f))
	}
	expr := fmt.Sprintf("eventheader_gen_eventheader.%s(%q%s)", f.Constructor, f.WireName, fieldOptions(f))
	switch f.Array {
	case "fixed":
		expr = fmt.Sprintf("eventheader_gen_eventheader.ArrayField(%s, eventheader_gen_eventheader.ArrayFixed, %d)", expr, f.Count)
	case "variable":
		expr = fmt.Sprintf("eventheader_gen_eventheader.ArrayField(%s, eventheader_gen_eventheader.ArrayVariable)", expr)
	}
	return expr
}

func renderBinding(out *strings.Builder, f field, expression, indent string, temp *int) {
	if f.Constructor == "StructField" {
		for _, child := range f.Children {
			renderBinding(out, child, expression+"."+child.GoName, indent, temp)
		}
		return
	}
	valueExpr := expression
	if f.NetType != "" {
		*temp++
		name := fmt.Sprintf("eventheaderGenIP%d", *temp)
		if f.NetType == "netip" {
			test := "Is4()"
			convert := "As4()"
			if f.Semantic == "ipv6" {
				test, convert = "Is6()", "As16()"
			}
			fmt.Fprintf(out, "%sif !%s.%s { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrInvalidValue) }\n", indent, expression, test, f.Path+": %w")
			fmt.Fprintf(out, "%s%s := %s.%s\n", indent, name, expression, convert)
		} else {
			convert := "To4()"
			if f.Semantic == "ipv6" {
				convert = "To16()"
				fmt.Fprintf(out, "%sif %s.To4() != nil { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrInvalidValue) }\n", indent, expression, f.Path+": %w")
			}
			fmt.Fprintf(out, "%s%sSlice := %s.%s\n", indent, name, expression, convert)
			fmt.Fprintf(out, "%sif %sSlice == nil { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrInvalidValue) }\n", indent, name, f.Path+": %w")
			fmt.Fprintf(out, "%svar %s %s\n%scopy(%s[:], %sSlice)\n", indent, name, f.BaseType, indent, name, name)
		}
		valueExpr = name
	} else if f.Array != "" {
		if f.DirectArray {
			valueExpr = expression
			if f.FixedOuter {
				valueExpr += "[:]"
			}
		} else {
			name := "w." + f.Scratch
			renderScratchResize(out, name, "[]"+f.BaseType, expression, indent)
			if f.ScratchBacking != "" {
				backing := "w." + f.ScratchBacking
				count := f.Scratch + "Count"
				offset := f.Scratch + "Offset"
				fmt.Fprintf(out, "%s%s := 0\n", indent, count)
				fmt.Fprintf(out, "%sfor i := range %s { %s += len(%s[i]) }\n", indent, expression, count, expression)
				fmt.Fprintf(out, "%sif cap(%s) < %s { %s = make(%s, %s) } else { %s = %s[:%s] }\n",
					indent, backing, count, backing, f.BaseType, count, backing, backing, count)
				fmt.Fprintf(out, "%s%s := 0\n", indent, offset)
				elementType := strings.TrimPrefix(f.BaseType, "[]")
				fmt.Fprintf(out, "%sfor i := range %s {\n", indent, expression)
				fmt.Fprintf(out, "%s\tfor j := range %s[i] { %s[%s+j] = %s(%s[i][j]) }\n",
					indent, expression, backing, offset, elementType, expression)
				fmt.Fprintf(out, "%s\t%s[i] = %s[%s:%s+len(%s[i])]\n",
					indent, name, backing, offset, offset, expression)
				fmt.Fprintf(out, "%s\t%s += len(%s[i])\n%s}\n", indent, offset, expression, indent)
			} else if f.Semantic == "binary-fixed" {
				fmt.Fprintf(out, "%sfor i := range %s { %s[i] = %s[i][:] }\n", indent, expression, name, expression)
			} else if f.ElementWise {
				fmt.Fprintf(out, "%sfor i := range %s {\n", indent, expression)
				fmt.Fprintf(out, "%s\tfor j := range %s[i] { %s[i][j] = byte(%s[i][j]) }\n",
					indent, expression, name, expression)
				fmt.Fprintf(out, "%s}\n", indent)
			} else {
				fmt.Fprintf(out, "%sfor i := range %s { %s[i] = %s(%s[i]) }\n", indent, expression, name, f.BaseType, expression)
			}
			valueExpr = name
		}
	} else if f.Scratch != "" {
		name := "w." + f.Scratch
		baseType := strings.TrimPrefix(f.BaseType, "[]")
		renderScratchResize(out, name, f.BaseType, expression, indent)
		fmt.Fprintf(out, "%sfor i := range %s { %s[i] = %s(%s[i]) }\n",
			indent, expression, name, baseType, expression)
		valueExpr = name
	} else if f.Semantic == "binary-fixed" {
		valueExpr = expression + "[:]"
	} else if f.ElementWise {
		*temp++
		name := fmt.Sprintf("eventheaderGenFixed%d", *temp)
		fmt.Fprintf(out, "%svar %s %s\n", indent, name, f.BaseType)
		fmt.Fprintf(out, "%sfor i := range %s { %s[i] = byte(%s[i]) }\n",
			indent, expression, name, expression)
		valueExpr = name
	} else if f.BaseType != "" && f.Semantic != "binary" && f.Semantic != "utf16" {
		valueExpr = fmt.Sprintf("%s(%s)", f.BaseType, expression)
	}
	fmt.Fprintf(out, "%sif err := w.binding.%s(%s); err != nil { return eventheader_gen_fmt.Errorf(%q, err) }\n",
		indent, f.Method, valueExpr, f.Path+": %w")
}

func renderScratchResize(out *strings.Builder, name, scratchType, expression, indent string) {
	fmt.Fprintf(out, "%sif cap(%s) < len(%s) {\n", indent, name, expression)
	fmt.Fprintf(out, "%s\tclear(%s)\n", indent, name)
	fmt.Fprintf(out, "%s\t%s = make(%s, len(%s))\n", indent, name, scratchType, expression)
	fmt.Fprintf(out, "%s} else {\n", indent)
	fmt.Fprintf(out, "%s\tif len(%s) > len(%s) { clear(%s[len(%s):]) }\n",
		indent, name, expression, name, expression)
	fmt.Fprintf(out, "%s\t%s = %s[:len(%s)]\n", indent, name, name, expression)
	fmt.Fprintf(out, "%s}\n", indent)
}

func renderScratchValidation(out *strings.Builder, f field, expression, indent string, temp *int) {
	const maxEventBytes = 65467
	countError := fmt.Sprintf("%s: %%w", f.Path)
	sizeError := countError

	if f.Array == "" {
		fmt.Fprintf(out, "%sif len(%s) > 65535 { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrCountTooLarge) }\n",
			indent, expression, countError)
		width := 1
		if f.BaseType == "[]uint16" {
			width = 2
		}
		fmt.Fprintf(out, "%sif len(%s) > (%d-2)/%d { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrEventTooLarge) }\n",
			indent, expression, maxEventBytes, width, sizeError)
		return
	}

	fmt.Fprintf(out, "%sif len(%s) > 65535 { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrCountTooLarge) }\n",
		indent, expression, countError)
	prefix := 0
	if f.Array == "variable" {
		prefix = 2
	}
	if f.BaseType == "[]byte" || f.BaseType == "[]uint16" || f.BaseType == "string" {
		width := 1
		if f.BaseType == "[]uint16" {
			width = 2
		}
		*temp++
		size := fmt.Sprintf("eventheaderGenSize%d", *temp)
		fmt.Fprintf(out, "%s%s := %d\n", indent, size, prefix)
		fmt.Fprintf(out, "%sfor i := range %s {\n", indent, expression)
		fmt.Fprintf(out, "%s\tif len(%s[i]) > 65535 { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrCountTooLarge) }\n",
			indent, expression, countError)
		fmt.Fprintf(out, "%s\tif %s > %d-2 || len(%s[i]) > (%d-%s-2)/%d { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrEventTooLarge) }\n",
			indent, size, maxEventBytes, expression, maxEventBytes, size, width, sizeError)
		fmt.Fprintf(out, "%s\t%s += 2 + len(%s[i]) * %d\n", indent, size, expression, width)
		fmt.Fprintf(out, "%s}\n", indent)
		return
	}

	width := scratchElementWireSize(f)
	fmt.Fprintf(out, "%sif len(%s) > (%d-%d)/(%s) { return eventheader_gen_fmt.Errorf(%q, eventheader_gen_eventheader.ErrEventTooLarge) }\n",
		indent, expression, maxEventBytes, prefix, width, sizeError)
}

func scratchElementWireSize(f field) string {
	switch f.BaseType {
	case "int8", "uint8", "byte", "bool":
		return "1"
	case "int16", "uint16":
		return "2"
	case "int32", "uint32", "rune", "float32", "[4]byte":
		return "4"
	case "int64", "uint64", "float64":
		return "8"
	case "uintptr":
		return "int(^uintptr(0)>>63)*4 + 4"
	case "[16]byte":
		return "16"
	default:
		panic("eventheader-gen: unknown scratch element type " + f.BaseType)
	}
}
