// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package generatedselection

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenSelectedASchemaOnce  eventheader_gen_sync.Once
	eventheaderGenSelectedASchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenSelectedASchemaErr   error
)

// SelectedASchema returns the immutable schema for SelectedA.
func SelectedASchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenSelectedASchemaOnce.Do(func() {
		eventheaderGenSelectedASchemaValue, eventheaderGenSelectedASchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "SelectedA", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint32Field("Value"),
		)
	})
	return eventheaderGenSelectedASchemaValue, eventheaderGenSelectedASchemaErr
}

// SelectedAWriter is goroutine-local reusable state for SelectedA.
type SelectedAWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewSelectedAWriter binds SelectedA to provider. A writer must be used by only one goroutine.
func NewSelectedAWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*SelectedAWriter, error) {
	schema, err := SelectedASchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &SelectedAWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the SelectedA event is enabled.
func (w *SelectedAWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }

// Event returns the reusable runtime event.
func (w *SelectedAWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *SelectedAWriter) Write(value *SelectedA, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

// WriteFunc constructs, encodes, and emits SelectedA only when enabled.
func (w *SelectedAWriter) WriteFunc(value func() (*SelectedA, error), activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	return w.event.WriteIfEnabled(&w.binding, activity, related, func(*eventheader_gen_eventheader.Binding) error {
		if value == nil {
			return eventheader_gen_fmt.Errorf("event value function: %w", eventheader_gen_eventheader.ErrInvalidValue)
		}
		eventValue, err := value()
		if err != nil {
			return err
		}
		return w.bind(eventValue)
	})
}

func (w *SelectedAWriter) bind(value *SelectedA) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint32(uint32(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("SelectedA.Value: %w", err)
	}
	return nil
}

var (
	eventheaderGenOmittedBSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenOmittedBSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenOmittedBSchemaErr   error
)

// OmittedBSchema returns the immutable schema for OmittedB.
func OmittedBSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenOmittedBSchemaOnce.Do(func() {
		eventheaderGenOmittedBSchemaValue, eventheaderGenOmittedBSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "OmittedB", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint32Field("Value"),
		)
	})
	return eventheaderGenOmittedBSchemaValue, eventheaderGenOmittedBSchemaErr
}

// OmittedBWriter is goroutine-local reusable state for OmittedB.
type OmittedBWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewOmittedBWriter binds OmittedB to provider. A writer must be used by only one goroutine.
func NewOmittedBWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*OmittedBWriter, error) {
	schema, err := OmittedBSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &OmittedBWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the OmittedB event is enabled.
func (w *OmittedBWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }

// Event returns the reusable runtime event.
func (w *OmittedBWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *OmittedBWriter) Write(value *OmittedB, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

// WriteFunc constructs, encodes, and emits OmittedB only when enabled.
func (w *OmittedBWriter) WriteFunc(value func() (*OmittedB, error), activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	return w.event.WriteIfEnabled(&w.binding, activity, related, func(*eventheader_gen_eventheader.Binding) error {
		if value == nil {
			return eventheader_gen_fmt.Errorf("event value function: %w", eventheader_gen_eventheader.ErrInvalidValue)
		}
		eventValue, err := value()
		if err != nil {
			return err
		}
		return w.bind(eventValue)
	})
}

func (w *OmittedBWriter) bind(value *OmittedB) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint32(uint32(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("OmittedB.Value: %w", err)
	}
	return nil
}
