//go:build amd64 && custom && linux

// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package constraints

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenCombinedLinuxAMD64EventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenCombinedLinuxAMD64EventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenCombinedLinuxAMD64EventSchemaErr   error
)

// CombinedLinuxAMD64EventSchema returns the immutable schema for CombinedLinuxAMD64Event.
func CombinedLinuxAMD64EventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenCombinedLinuxAMD64EventSchemaOnce.Do(func() {
		eventheaderGenCombinedLinuxAMD64EventSchemaValue, eventheaderGenCombinedLinuxAMD64EventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "CombinedLinuxAMD64Event", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint64Field("Value"),
		)
	})
	return eventheaderGenCombinedLinuxAMD64EventSchemaValue, eventheaderGenCombinedLinuxAMD64EventSchemaErr
}

// CombinedLinuxAMD64EventWriter is goroutine-local reusable state for CombinedLinuxAMD64Event.
type CombinedLinuxAMD64EventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewCombinedLinuxAMD64EventWriter binds CombinedLinuxAMD64Event to provider. A writer must be used by only one goroutine.
func NewCombinedLinuxAMD64EventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*CombinedLinuxAMD64EventWriter, error) {
	schema, err := CombinedLinuxAMD64EventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &CombinedLinuxAMD64EventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the CombinedLinuxAMD64Event event is enabled.
func (w *CombinedLinuxAMD64EventWriter) Enabled() bool {
	return w != nil && w.event != nil && w.event.Enabled()
}

// Event returns the reusable runtime event.
func (w *CombinedLinuxAMD64EventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *CombinedLinuxAMD64EventWriter) Write(value *CombinedLinuxAMD64Event, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

// WriteFunc constructs, encodes, and emits CombinedLinuxAMD64Event only when enabled.
func (w *CombinedLinuxAMD64EventWriter) WriteFunc(value func() (*CombinedLinuxAMD64Event, error), activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	return w.event.WriteIfEnabled(&w.binding, activity, related, func(*eventheader_gen_eventheader.Binding) error {
		if value == nil {
			return eventheader_gen_fmt.Errorf("event value function: %w", eventheader_gen_eventheader.ErrInvalidValue)
		}
		eventValue, err := value()
		if err != nil {
			return err
		}
		return w.bind(eventValue)
	})
}

func (w *CombinedLinuxAMD64EventWriter) bind(value *CombinedLinuxAMD64Event) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint64(uint64(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("CombinedLinuxAMD64Event.Value: %w", err)
	}
	return nil
}
