//go:build custom

// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package constraints

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenCustomEventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenCustomEventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenCustomEventSchemaErr   error
)

// CustomEventSchema returns the immutable schema for CustomEvent.
func CustomEventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenCustomEventSchemaOnce.Do(func() {
		eventheaderGenCustomEventSchemaValue, eventheaderGenCustomEventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "CustomEvent", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint64Field("Value"),
		)
	})
	return eventheaderGenCustomEventSchemaValue, eventheaderGenCustomEventSchemaErr
}

// CustomEventWriter is goroutine-local reusable state for CustomEvent.
type CustomEventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewCustomEventWriter binds CustomEvent to provider. A writer must be used by only one goroutine.
func NewCustomEventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*CustomEventWriter, error) {
	schema, err := CustomEventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &CustomEventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the CustomEvent event is enabled.
func (w *CustomEventWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }

// Event returns the reusable runtime event.
func (w *CustomEventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *CustomEventWriter) Write(value *CustomEvent, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

func (w *CustomEventWriter) bind(value *CustomEvent) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint64(uint64(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("CustomEvent.Value: %w", err)
	}
	return nil
}
