//go:build amd64 && linux

// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package constraints

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenFilenameLinuxAMD64EventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenFilenameLinuxAMD64EventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenFilenameLinuxAMD64EventSchemaErr   error
)

// FilenameLinuxAMD64EventSchema returns the immutable schema for FilenameLinuxAMD64Event.
func FilenameLinuxAMD64EventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenFilenameLinuxAMD64EventSchemaOnce.Do(func() {
		eventheaderGenFilenameLinuxAMD64EventSchemaValue, eventheaderGenFilenameLinuxAMD64EventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "FilenameLinuxAMD64Event", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint16Field("Value"),
		)
	})
	return eventheaderGenFilenameLinuxAMD64EventSchemaValue, eventheaderGenFilenameLinuxAMD64EventSchemaErr
}

// FilenameLinuxAMD64EventWriter is goroutine-local reusable state for FilenameLinuxAMD64Event.
type FilenameLinuxAMD64EventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewFilenameLinuxAMD64EventWriter binds FilenameLinuxAMD64Event to provider. A writer must be used by only one goroutine.
func NewFilenameLinuxAMD64EventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*FilenameLinuxAMD64EventWriter, error) {
	schema, err := FilenameLinuxAMD64EventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &FilenameLinuxAMD64EventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the FilenameLinuxAMD64Event event is enabled.
func (w *FilenameLinuxAMD64EventWriter) Enabled() bool {
	return w != nil && w.event != nil && w.event.Enabled()
}

// Event returns the reusable runtime event.
func (w *FilenameLinuxAMD64EventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *FilenameLinuxAMD64EventWriter) Write(value *FilenameLinuxAMD64Event, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

// WriteFunc constructs, encodes, and emits FilenameLinuxAMD64Event only when enabled.
func (w *FilenameLinuxAMD64EventWriter) WriteFunc(value func() (*FilenameLinuxAMD64Event, error), activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	return w.event.WriteIfEnabled(&w.binding, activity, related, func(*eventheader_gen_eventheader.Binding) error {
		if value == nil {
			return eventheader_gen_fmt.Errorf("event value function: %w", eventheader_gen_eventheader.ErrInvalidValue)
		}
		eventValue, err := value()
		if err != nil {
			return err
		}
		return w.bind(eventValue)
	})
}

func (w *FilenameLinuxAMD64EventWriter) bind(value *FilenameLinuxAMD64Event) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint16(uint16(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("FilenameLinuxAMD64Event.Value: %w", err)
	}
	return nil
}
