//go:build linux

// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package constraints

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenFilenameLinuxEventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenFilenameLinuxEventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenFilenameLinuxEventSchemaErr   error
)

// FilenameLinuxEventSchema returns the immutable schema for FilenameLinuxEvent.
func FilenameLinuxEventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenFilenameLinuxEventSchemaOnce.Do(func() {
		eventheaderGenFilenameLinuxEventSchemaValue, eventheaderGenFilenameLinuxEventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "FilenameLinuxEvent", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint8Field("Value"),
		)
	})
	return eventheaderGenFilenameLinuxEventSchemaValue, eventheaderGenFilenameLinuxEventSchemaErr
}

// FilenameLinuxEventWriter is goroutine-local reusable state for FilenameLinuxEvent.
type FilenameLinuxEventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewFilenameLinuxEventWriter binds FilenameLinuxEvent to provider. A writer must be used by only one goroutine.
func NewFilenameLinuxEventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*FilenameLinuxEventWriter, error) {
	schema, err := FilenameLinuxEventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &FilenameLinuxEventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the FilenameLinuxEvent event is enabled.
func (w *FilenameLinuxEventWriter) Enabled() bool {
	return w != nil && w.event != nil && w.event.Enabled()
}

// Event returns the reusable runtime event.
func (w *FilenameLinuxEventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *FilenameLinuxEventWriter) Write(value *FilenameLinuxEvent, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

// WriteFunc constructs, encodes, and emits FilenameLinuxEvent only when enabled.
func (w *FilenameLinuxEventWriter) WriteFunc(value func() (*FilenameLinuxEvent, error), activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	return w.event.WriteIfEnabled(&w.binding, activity, related, func(*eventheader_gen_eventheader.Binding) error {
		if value == nil {
			return eventheader_gen_fmt.Errorf("event value function: %w", eventheader_gen_eventheader.ErrInvalidValue)
		}
		eventValue, err := value()
		if err != nil {
			return err
		}
		return w.bind(eventValue)
	})
}

func (w *FilenameLinuxEventWriter) bind(value *FilenameLinuxEvent) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint8(uint8(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("FilenameLinuxEvent.Value: %w", err)
	}
	return nil
}
