//go:build amd64

// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package constraints

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenFilenameAMD64EventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenFilenameAMD64EventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenFilenameAMD64EventSchemaErr   error
)

// FilenameAMD64EventSchema returns the immutable schema for FilenameAMD64Event.
func FilenameAMD64EventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenFilenameAMD64EventSchemaOnce.Do(func() {
		eventheaderGenFilenameAMD64EventSchemaValue, eventheaderGenFilenameAMD64EventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "FilenameAMD64Event", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint32Field("Value"),
		)
	})
	return eventheaderGenFilenameAMD64EventSchemaValue, eventheaderGenFilenameAMD64EventSchemaErr
}

// FilenameAMD64EventWriter is goroutine-local reusable state for FilenameAMD64Event.
type FilenameAMD64EventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewFilenameAMD64EventWriter binds FilenameAMD64Event to provider. A writer must be used by only one goroutine.
func NewFilenameAMD64EventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*FilenameAMD64EventWriter, error) {
	schema, err := FilenameAMD64EventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &FilenameAMD64EventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the FilenameAMD64Event event is enabled.
func (w *FilenameAMD64EventWriter) Enabled() bool {
	return w != nil && w.event != nil && w.event.Enabled()
}

// Event returns the reusable runtime event.
func (w *FilenameAMD64EventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *FilenameAMD64EventWriter) Write(value *FilenameAMD64Event, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

func (w *FilenameAMD64EventWriter) bind(value *FilenameAMD64Event) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint32(uint32(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("FilenameAMD64Event.Value: %w", err)
	}
	return nil
}
