//go:build linux

// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package constraints

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenLinuxEventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenLinuxEventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenLinuxEventSchemaErr   error
)

// LinuxEventSchema returns the immutable schema for LinuxEvent.
func LinuxEventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenLinuxEventSchemaOnce.Do(func() {
		eventheaderGenLinuxEventSchemaValue, eventheaderGenLinuxEventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "LinuxEvent", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint32Field("Value"),
		)
	})
	return eventheaderGenLinuxEventSchemaValue, eventheaderGenLinuxEventSchemaErr
}

// LinuxEventWriter is goroutine-local reusable state for LinuxEvent.
type LinuxEventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewLinuxEventWriter binds LinuxEvent to provider. A writer must be used by only one goroutine.
func NewLinuxEventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*LinuxEventWriter, error) {
	schema, err := LinuxEventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &LinuxEventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the LinuxEvent event is enabled.
func (w *LinuxEventWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }

// Event returns the reusable runtime event.
func (w *LinuxEventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *LinuxEventWriter) Write(value *LinuxEvent, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

func (w *LinuxEventWriter) bind(value *LinuxEvent) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint32(uint32(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("LinuxEvent.Value: %w", err)
	}
	return nil
}
