// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package eventheaderfixture

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenRequestEventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenRequestEventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenRequestEventSchemaErr   error
)

// RequestEventSchema returns the immutable schema for RequestEvent.
func RequestEventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenRequestEventSchemaOnce.Do(func() {
		eventheaderGenRequestEventSchemaValue, eventheaderGenRequestEventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "Request", ID: 12, Version: 2, Tag: 7, Opcode: 0},
			eventheader_gen_eventheader.UUIDField("request_id"),
			eventheader_gen_eventheader.IPv4Field("NamedIPv4"),
			eventheader_gen_eventheader.IPv6Field("NamedIPv6"),
			eventheader_gen_eventheader.UUIDField("NamedUUID"),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.IPv4Field("NamedIPv4s"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.IPv6Field("NamedIPv6s"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.UUIDField("NamedUUIDs"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.IPv4Field("FixedNamedIPv4"), eventheader_gen_eventheader.ArrayFixed, 2),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.IPv6Field("FixedNamedIPv6"), eventheader_gen_eventheader.ArrayFixed, 2),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.UUIDField("FixedNamedUUID"), eventheader_gen_eventheader.ArrayFixed, 2),
			eventheader_gen_eventheader.IPv4Field("client"),
			eventheader_gen_eventheader.Uint16Field("Status", eventheader_gen_eventheader.FieldOptions{Format: eventheader_gen_eventheader.FormatHexInt, Tag: 3}),
			eventheader_gen_eventheader.BoolField("Enabled"),
			eventheader_gen_eventheader.StringField("Label"),
			eventheader_gen_eventheader.StructField("Details", []eventheader_gen_eventheader.FieldDefinition{eventheader_gen_eventheader.StringField("Method"), eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.Uint32Field("Attempts", eventheader_gen_eventheader.FieldOptions{Format: eventheader_gen_eventheader.FormatUnsignedInt, Tag: 0}), eventheader_gen_eventheader.ArrayFixed, 2)}),
			eventheader_gen_eventheader.BinaryField("Payload"),
			eventheader_gen_eventheader.BinaryField("Raw"),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.Uint8Field("Bytes"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.UTF16Field("Message"),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.Int32Field("Counts"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.UintptrField("Pointers"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.BinaryField("Blocks"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.UTF16Field("Words"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.BinaryField("NamedBlobs"), eventheader_gen_eventheader.ArrayVariable),
		)
	})
	return eventheaderGenRequestEventSchemaValue, eventheaderGenRequestEventSchemaErr
}

// RequestEventWriter is goroutine-local reusable state for RequestEvent.
type RequestEventWriter struct {
	event                   *eventheader_gen_eventheader.Event
	binding                 eventheader_gen_eventheader.Binding
	eventheaderGenScratch1  [][4]byte
	eventheaderGenScratch2  [][16]byte
	eventheaderGenScratch3  [][16]byte
	eventheaderGenScratch4  [][4]byte
	eventheaderGenScratch5  [][16]byte
	eventheaderGenScratch6  [][16]byte
	eventheaderGenScratch7  []byte
	eventheaderGenScratch8  []byte
	eventheaderGenScratch9  []uint16
	eventheaderGenScratch10 []int32
	eventheaderGenScratch11 []uintptr
	eventheaderGenScratch12 [][]byte
	eventheaderGenScratch13 []byte
	eventheaderGenScratch14 [][]uint16
	eventheaderGenScratch15 []uint16
	eventheaderGenScratch16 [][]byte
	eventheaderGenScratch17 []byte
}

// NewRequestEventWriter binds RequestEvent to provider. A writer must be used by only one goroutine.
func NewRequestEventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*RequestEventWriter, error) {
	schema, err := RequestEventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x10, "http")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &RequestEventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the Request event is enabled.
func (w *RequestEventWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }

// Event returns the reusable runtime event.
func (w *RequestEventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *RequestEventWriter) Write(value *RequestEvent, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

func (w *RequestEventWriter) bind(value *RequestEvent) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	if len(value.NamedIPv4s) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv4s: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.NamedIPv4s) > (65467-2)/(4) {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv4s: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.NamedIPv6s) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv6s: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.NamedIPv6s) > (65467-2)/(16) {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv6s: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.NamedUUIDs) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedUUIDs: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.NamedUUIDs) > (65467-2)/(16) {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedUUIDs: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.FixedNamedIPv4) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedIPv4: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.FixedNamedIPv4) > (65467-0)/(4) {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedIPv4: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.FixedNamedIPv6) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedIPv6: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.FixedNamedIPv6) > (65467-0)/(16) {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedIPv6: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.FixedNamedUUID) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedUUID: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.FixedNamedUUID) > (65467-0)/(16) {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedUUID: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.Payload) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Payload: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.Payload) > (65467-2)/1 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Payload: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.Raw) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Raw: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.Raw) > (65467-2)/1 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Raw: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.Message) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Message: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.Message) > (65467-2)/2 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Message: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.Counts) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Counts: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.Counts) > (65467-2)/(4) {
		return eventheader_gen_fmt.Errorf("RequestEvent.Counts: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.Pointers) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Pointers: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	if len(value.Pointers) > (65467-2)/(int(^uintptr(0)>>63)*4+4) {
		return eventheader_gen_fmt.Errorf("RequestEvent.Pointers: %w", eventheader_gen_eventheader.ErrEventTooLarge)
	}
	if len(value.Blocks) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Blocks: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	eventheaderGenSize1 := 2
	for i := range value.Blocks {
		if len(value.Blocks[i]) > 65535 {
			return eventheader_gen_fmt.Errorf("RequestEvent.Blocks: %w", eventheader_gen_eventheader.ErrCountTooLarge)
		}
		if eventheaderGenSize1 > 65467-2 || len(value.Blocks[i]) > (65467-eventheaderGenSize1-2)/1 {
			return eventheader_gen_fmt.Errorf("RequestEvent.Blocks: %w", eventheader_gen_eventheader.ErrEventTooLarge)
		}
		eventheaderGenSize1 += 2 + len(value.Blocks[i])*1
	}
	if len(value.Words) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.Words: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	eventheaderGenSize2 := 2
	for i := range value.Words {
		if len(value.Words[i]) > 65535 {
			return eventheader_gen_fmt.Errorf("RequestEvent.Words: %w", eventheader_gen_eventheader.ErrCountTooLarge)
		}
		if eventheaderGenSize2 > 65467-2 || len(value.Words[i]) > (65467-eventheaderGenSize2-2)/2 {
			return eventheader_gen_fmt.Errorf("RequestEvent.Words: %w", eventheader_gen_eventheader.ErrEventTooLarge)
		}
		eventheaderGenSize2 += 2 + len(value.Words[i])*2
	}
	if len(value.NamedBlobs) > 65535 {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedBlobs: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	eventheaderGenSize3 := 2
	for i := range value.NamedBlobs {
		if len(value.NamedBlobs[i]) > 65535 {
			return eventheader_gen_fmt.Errorf("RequestEvent.NamedBlobs: %w", eventheader_gen_eventheader.ErrCountTooLarge)
		}
		if eventheaderGenSize3 > 65467-2 || len(value.NamedBlobs[i]) > (65467-eventheaderGenSize3-2)/1 {
			return eventheader_gen_fmt.Errorf("RequestEvent.NamedBlobs: %w", eventheader_gen_eventheader.ErrEventTooLarge)
		}
		eventheaderGenSize3 += 2 + len(value.NamedBlobs[i])*1
	}
	w.binding.Reset()
	if err := w.binding.UUID([16]byte(value.RequestID)); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.RequestID: %w", err)
	}
	var eventheaderGenFixed4 [4]byte
	for i := range value.NamedIPv4 {
		eventheaderGenFixed4[i] = byte(value.NamedIPv4[i])
	}
	if err := w.binding.IPv4(eventheaderGenFixed4); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv4: %w", err)
	}
	var eventheaderGenFixed5 [16]byte
	for i := range value.NamedIPv6 {
		eventheaderGenFixed5[i] = byte(value.NamedIPv6[i])
	}
	if err := w.binding.IPv6(eventheaderGenFixed5); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv6: %w", err)
	}
	var eventheaderGenFixed6 [16]byte
	for i := range value.NamedUUID {
		eventheaderGenFixed6[i] = byte(value.NamedUUID[i])
	}
	if err := w.binding.UUID(eventheaderGenFixed6); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedUUID: %w", err)
	}
	if cap(w.eventheaderGenScratch1) < len(value.NamedIPv4s) {
		clear(w.eventheaderGenScratch1)
		w.eventheaderGenScratch1 = make([][4]byte, len(value.NamedIPv4s))
	} else {
		if len(w.eventheaderGenScratch1) > len(value.NamedIPv4s) {
			clear(w.eventheaderGenScratch1[len(value.NamedIPv4s):])
		}
		w.eventheaderGenScratch1 = w.eventheaderGenScratch1[:len(value.NamedIPv4s)]
	}
	for i := range value.NamedIPv4s {
		for j := range value.NamedIPv4s[i] {
			w.eventheaderGenScratch1[i][j] = byte(value.NamedIPv4s[i][j])
		}
	}
	if err := w.binding.IPv4Array(w.eventheaderGenScratch1); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv4s: %w", err)
	}
	if cap(w.eventheaderGenScratch2) < len(value.NamedIPv6s) {
		clear(w.eventheaderGenScratch2)
		w.eventheaderGenScratch2 = make([][16]byte, len(value.NamedIPv6s))
	} else {
		if len(w.eventheaderGenScratch2) > len(value.NamedIPv6s) {
			clear(w.eventheaderGenScratch2[len(value.NamedIPv6s):])
		}
		w.eventheaderGenScratch2 = w.eventheaderGenScratch2[:len(value.NamedIPv6s)]
	}
	for i := range value.NamedIPv6s {
		for j := range value.NamedIPv6s[i] {
			w.eventheaderGenScratch2[i][j] = byte(value.NamedIPv6s[i][j])
		}
	}
	if err := w.binding.IPv6Array(w.eventheaderGenScratch2); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedIPv6s: %w", err)
	}
	if cap(w.eventheaderGenScratch3) < len(value.NamedUUIDs) {
		clear(w.eventheaderGenScratch3)
		w.eventheaderGenScratch3 = make([][16]byte, len(value.NamedUUIDs))
	} else {
		if len(w.eventheaderGenScratch3) > len(value.NamedUUIDs) {
			clear(w.eventheaderGenScratch3[len(value.NamedUUIDs):])
		}
		w.eventheaderGenScratch3 = w.eventheaderGenScratch3[:len(value.NamedUUIDs)]
	}
	for i := range value.NamedUUIDs {
		for j := range value.NamedUUIDs[i] {
			w.eventheaderGenScratch3[i][j] = byte(value.NamedUUIDs[i][j])
		}
	}
	if err := w.binding.UUIDArray(w.eventheaderGenScratch3); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedUUIDs: %w", err)
	}
	if cap(w.eventheaderGenScratch4) < len(value.FixedNamedIPv4) {
		clear(w.eventheaderGenScratch4)
		w.eventheaderGenScratch4 = make([][4]byte, len(value.FixedNamedIPv4))
	} else {
		if len(w.eventheaderGenScratch4) > len(value.FixedNamedIPv4) {
			clear(w.eventheaderGenScratch4[len(value.FixedNamedIPv4):])
		}
		w.eventheaderGenScratch4 = w.eventheaderGenScratch4[:len(value.FixedNamedIPv4)]
	}
	for i := range value.FixedNamedIPv4 {
		for j := range value.FixedNamedIPv4[i] {
			w.eventheaderGenScratch4[i][j] = byte(value.FixedNamedIPv4[i][j])
		}
	}
	if err := w.binding.IPv4Array(w.eventheaderGenScratch4); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedIPv4: %w", err)
	}
	if cap(w.eventheaderGenScratch5) < len(value.FixedNamedIPv6) {
		clear(w.eventheaderGenScratch5)
		w.eventheaderGenScratch5 = make([][16]byte, len(value.FixedNamedIPv6))
	} else {
		if len(w.eventheaderGenScratch5) > len(value.FixedNamedIPv6) {
			clear(w.eventheaderGenScratch5[len(value.FixedNamedIPv6):])
		}
		w.eventheaderGenScratch5 = w.eventheaderGenScratch5[:len(value.FixedNamedIPv6)]
	}
	for i := range value.FixedNamedIPv6 {
		for j := range value.FixedNamedIPv6[i] {
			w.eventheaderGenScratch5[i][j] = byte(value.FixedNamedIPv6[i][j])
		}
	}
	if err := w.binding.IPv6Array(w.eventheaderGenScratch5); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedIPv6: %w", err)
	}
	if cap(w.eventheaderGenScratch6) < len(value.FixedNamedUUID) {
		clear(w.eventheaderGenScratch6)
		w.eventheaderGenScratch6 = make([][16]byte, len(value.FixedNamedUUID))
	} else {
		if len(w.eventheaderGenScratch6) > len(value.FixedNamedUUID) {
			clear(w.eventheaderGenScratch6[len(value.FixedNamedUUID):])
		}
		w.eventheaderGenScratch6 = w.eventheaderGenScratch6[:len(value.FixedNamedUUID)]
	}
	for i := range value.FixedNamedUUID {
		for j := range value.FixedNamedUUID[i] {
			w.eventheaderGenScratch6[i][j] = byte(value.FixedNamedUUID[i][j])
		}
	}
	if err := w.binding.UUIDArray(w.eventheaderGenScratch6); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.FixedNamedUUID: %w", err)
	}
	if !value.Client.Is4() {
		return eventheader_gen_fmt.Errorf("RequestEvent.Client: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	eventheaderGenIP7 := value.Client.As4()
	if err := w.binding.IPv4(eventheaderGenIP7); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Client: %w", err)
	}
	if err := w.binding.Uint16(uint16(value.Status)); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Status: %w", err)
	}
	if err := w.binding.Bool(bool(value.Enabled)); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Enabled: %w", err)
	}
	if err := w.binding.String(string(value.Label)); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Label: %w", err)
	}
	if err := w.binding.String(string(value.Details.Method)); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Details.Method: %w", err)
	}
	if err := w.binding.Uint32Array(value.Details.Attempts[:]); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Details.Attempts: %w", err)
	}
	if cap(w.eventheaderGenScratch7) < len(value.Payload) {
		clear(w.eventheaderGenScratch7)
		w.eventheaderGenScratch7 = make([]byte, len(value.Payload))
	} else {
		if len(w.eventheaderGenScratch7) > len(value.Payload) {
			clear(w.eventheaderGenScratch7[len(value.Payload):])
		}
		w.eventheaderGenScratch7 = w.eventheaderGenScratch7[:len(value.Payload)]
	}
	for i := range value.Payload {
		w.eventheaderGenScratch7[i] = byte(value.Payload[i])
	}
	if err := w.binding.Binary(w.eventheaderGenScratch7); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Payload: %w", err)
	}
	if cap(w.eventheaderGenScratch8) < len(value.Raw) {
		clear(w.eventheaderGenScratch8)
		w.eventheaderGenScratch8 = make([]byte, len(value.Raw))
	} else {
		if len(w.eventheaderGenScratch8) > len(value.Raw) {
			clear(w.eventheaderGenScratch8[len(value.Raw):])
		}
		w.eventheaderGenScratch8 = w.eventheaderGenScratch8[:len(value.Raw)]
	}
	for i := range value.Raw {
		w.eventheaderGenScratch8[i] = byte(value.Raw[i])
	}
	if err := w.binding.Binary(w.eventheaderGenScratch8); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Raw: %w", err)
	}
	if err := w.binding.Uint8Array(value.Bytes); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Bytes: %w", err)
	}
	if cap(w.eventheaderGenScratch9) < len(value.Message) {
		clear(w.eventheaderGenScratch9)
		w.eventheaderGenScratch9 = make([]uint16, len(value.Message))
	} else {
		if len(w.eventheaderGenScratch9) > len(value.Message) {
			clear(w.eventheaderGenScratch9[len(value.Message):])
		}
		w.eventheaderGenScratch9 = w.eventheaderGenScratch9[:len(value.Message)]
	}
	for i := range value.Message {
		w.eventheaderGenScratch9[i] = uint16(value.Message[i])
	}
	if err := w.binding.UTF16(w.eventheaderGenScratch9); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Message: %w", err)
	}
	if cap(w.eventheaderGenScratch10) < len(value.Counts) {
		clear(w.eventheaderGenScratch10)
		w.eventheaderGenScratch10 = make([]int32, len(value.Counts))
	} else {
		if len(w.eventheaderGenScratch10) > len(value.Counts) {
			clear(w.eventheaderGenScratch10[len(value.Counts):])
		}
		w.eventheaderGenScratch10 = w.eventheaderGenScratch10[:len(value.Counts)]
	}
	for i := range value.Counts {
		w.eventheaderGenScratch10[i] = int32(value.Counts[i])
	}
	if err := w.binding.Int32Array(w.eventheaderGenScratch10); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Counts: %w", err)
	}
	if cap(w.eventheaderGenScratch11) < len(value.Pointers) {
		clear(w.eventheaderGenScratch11)
		w.eventheaderGenScratch11 = make([]uintptr, len(value.Pointers))
	} else {
		if len(w.eventheaderGenScratch11) > len(value.Pointers) {
			clear(w.eventheaderGenScratch11[len(value.Pointers):])
		}
		w.eventheaderGenScratch11 = w.eventheaderGenScratch11[:len(value.Pointers)]
	}
	for i := range value.Pointers {
		w.eventheaderGenScratch11[i] = uintptr(value.Pointers[i])
	}
	if err := w.binding.UintptrArray(w.eventheaderGenScratch11); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Pointers: %w", err)
	}
	if cap(w.eventheaderGenScratch12) < len(value.Blocks) {
		clear(w.eventheaderGenScratch12)
		w.eventheaderGenScratch12 = make([][]byte, len(value.Blocks))
	} else {
		if len(w.eventheaderGenScratch12) > len(value.Blocks) {
			clear(w.eventheaderGenScratch12[len(value.Blocks):])
		}
		w.eventheaderGenScratch12 = w.eventheaderGenScratch12[:len(value.Blocks)]
	}
	eventheaderGenScratch12Count := 0
	for i := range value.Blocks {
		eventheaderGenScratch12Count += len(value.Blocks[i])
	}
	if cap(w.eventheaderGenScratch13) < eventheaderGenScratch12Count {
		w.eventheaderGenScratch13 = make([]byte, eventheaderGenScratch12Count)
	} else {
		w.eventheaderGenScratch13 = w.eventheaderGenScratch13[:eventheaderGenScratch12Count]
	}
	eventheaderGenScratch12Offset := 0
	for i := range value.Blocks {
		for j := range value.Blocks[i] {
			w.eventheaderGenScratch13[eventheaderGenScratch12Offset+j] = byte(value.Blocks[i][j])
		}
		w.eventheaderGenScratch12[i] = w.eventheaderGenScratch13[eventheaderGenScratch12Offset : eventheaderGenScratch12Offset+len(value.Blocks[i])]
		eventheaderGenScratch12Offset += len(value.Blocks[i])
	}
	if err := w.binding.BinaryArray(w.eventheaderGenScratch12); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Blocks: %w", err)
	}
	if cap(w.eventheaderGenScratch14) < len(value.Words) {
		clear(w.eventheaderGenScratch14)
		w.eventheaderGenScratch14 = make([][]uint16, len(value.Words))
	} else {
		if len(w.eventheaderGenScratch14) > len(value.Words) {
			clear(w.eventheaderGenScratch14[len(value.Words):])
		}
		w.eventheaderGenScratch14 = w.eventheaderGenScratch14[:len(value.Words)]
	}
	eventheaderGenScratch14Count := 0
	for i := range value.Words {
		eventheaderGenScratch14Count += len(value.Words[i])
	}
	if cap(w.eventheaderGenScratch15) < eventheaderGenScratch14Count {
		w.eventheaderGenScratch15 = make([]uint16, eventheaderGenScratch14Count)
	} else {
		w.eventheaderGenScratch15 = w.eventheaderGenScratch15[:eventheaderGenScratch14Count]
	}
	eventheaderGenScratch14Offset := 0
	for i := range value.Words {
		for j := range value.Words[i] {
			w.eventheaderGenScratch15[eventheaderGenScratch14Offset+j] = uint16(value.Words[i][j])
		}
		w.eventheaderGenScratch14[i] = w.eventheaderGenScratch15[eventheaderGenScratch14Offset : eventheaderGenScratch14Offset+len(value.Words[i])]
		eventheaderGenScratch14Offset += len(value.Words[i])
	}
	if err := w.binding.UTF16Array(w.eventheaderGenScratch14); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.Words: %w", err)
	}
	if cap(w.eventheaderGenScratch16) < len(value.NamedBlobs) {
		clear(w.eventheaderGenScratch16)
		w.eventheaderGenScratch16 = make([][]byte, len(value.NamedBlobs))
	} else {
		if len(w.eventheaderGenScratch16) > len(value.NamedBlobs) {
			clear(w.eventheaderGenScratch16[len(value.NamedBlobs):])
		}
		w.eventheaderGenScratch16 = w.eventheaderGenScratch16[:len(value.NamedBlobs)]
	}
	eventheaderGenScratch16Count := 0
	for i := range value.NamedBlobs {
		eventheaderGenScratch16Count += len(value.NamedBlobs[i])
	}
	if cap(w.eventheaderGenScratch17) < eventheaderGenScratch16Count {
		w.eventheaderGenScratch17 = make([]byte, eventheaderGenScratch16Count)
	} else {
		w.eventheaderGenScratch17 = w.eventheaderGenScratch17[:eventheaderGenScratch16Count]
	}
	eventheaderGenScratch16Offset := 0
	for i := range value.NamedBlobs {
		for j := range value.NamedBlobs[i] {
			w.eventheaderGenScratch17[eventheaderGenScratch16Offset+j] = byte(value.NamedBlobs[i][j])
		}
		w.eventheaderGenScratch16[i] = w.eventheaderGenScratch17[eventheaderGenScratch16Offset : eventheaderGenScratch16Offset+len(value.NamedBlobs[i])]
		eventheaderGenScratch16Offset += len(value.NamedBlobs[i])
	}
	if err := w.binding.BinaryArray(w.eventheaderGenScratch16); err != nil {
		return eventheader_gen_fmt.Errorf("RequestEvent.NamedBlobs: %w", err)
	}
	return nil
}
