// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package methodcollisionstale

type CollisionEventWriter struct{}

func (*CollisionEventWriter) Enabled() bool { return false }
