// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package stale

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenStaleEventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenStaleEventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenStaleEventSchemaErr   error
)

// StaleEventSchema returns the immutable schema for StaleEvent.
func StaleEventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenStaleEventSchemaOnce.Do(func() {
		eventheaderGenStaleEventSchemaValue, eventheaderGenStaleEventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "StaleEvent", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.Uint32Field("Value"),
		)
	})
	return eventheaderGenStaleEventSchemaValue, eventheaderGenStaleEventSchemaErr
}

// StaleEventWriter is goroutine-local reusable state for StaleEvent.
type StaleEventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewStaleEventWriter binds StaleEvent to provider. A writer must be used by only one goroutine.
func NewStaleEventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*StaleEventWriter, error) {
	schema, err := StaleEventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &StaleEventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the StaleEvent event is enabled.
func (w *StaleEventWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }

// Event returns the reusable runtime event.
func (w *StaleEventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *StaleEventWriter) Write(value *StaleEvent, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

func (w *StaleEventWriter) bind(value *StaleEvent) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint32(uint32(value.Value)); err != nil {
		return eventheader_gen_fmt.Errorf("StaleEvent.Value: %w", err)
	}
	return nil
}

// Intentionally stale.
