// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package golden

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenGoldenEventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenGoldenEventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenGoldenEventSchemaErr   error
)

// GoldenEventSchema returns the immutable schema for GoldenEvent.
func GoldenEventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenGoldenEventSchemaOnce.Do(func() {
		eventheaderGenGoldenEventSchemaValue, eventheaderGenGoldenEventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "Golden", ID: 65535, Version: 255, Tag: 9, Opcode: 1},
			eventheader_gen_eventheader.UUIDField("id", eventheader_gen_eventheader.FieldOptions{Format: eventheader_gen_eventheader.FormatDefault, Tag: 1}),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.UUIDField("ids"), eventheader_gen_eventheader.ArrayFixed, 2),
			eventheader_gen_eventheader.Uint32Field("code", eventheader_gen_eventheader.FieldOptions{Format: eventheader_gen_eventheader.FormatHexInt, Tag: 0}),
			eventheader_gen_eventheader.BoolField("Enabled"),
			eventheader_gen_eventheader.StringField("Message"),
			eventheader_gen_eventheader.Int64Field("Elapsed"),
			eventheader_gen_eventheader.IPv6Field("address"),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.Int32Field("Values"), eventheader_gen_eventheader.ArrayFixed, 2),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.BinaryField("Blobs"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.StringField("Messages"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.BinaryField("NamedBlobs"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.UTF16Field("UTF16Text"), eventheader_gen_eventheader.ArrayVariable),
			eventheader_gen_eventheader.BinaryField("raw"),
			eventheader_gen_eventheader.StructField("Detail", []eventheader_gen_eventheader.FieldDefinition{eventheader_gen_eventheader.PortField("count"), eventheader_gen_eventheader.StringField("Text", eventheader_gen_eventheader.FieldOptions{Format: eventheader_gen_eventheader.FormatStringJSON, Tag: 0})}),
			eventheader_gen_eventheader.BinaryField("Data"),
		)
	})
	return eventheaderGenGoldenEventSchemaValue, eventheaderGenGoldenEventSchemaErr
}

// GoldenEventWriter is goroutine-local reusable state for GoldenEvent.
type GoldenEventWriter struct {
	event                  *eventheader_gen_eventheader.Event
	binding                eventheader_gen_eventheader.Binding
	eventheaderGenScratch1 []string
	eventheaderGenScratch2 [][]byte
	eventheaderGenScratch3 [][]uint16
}

// NewGoldenEventWriter binds GoldenEvent to provider. A writer must be used by only one goroutine.
func NewGoldenEventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*GoldenEventWriter, error) {
	schema, err := GoldenEventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(3, 0x42, "api")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &GoldenEventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the Golden event is enabled.
func (w *GoldenEventWriter) Enabled() bool { return w != nil && w.event != nil && w.event.Enabled() }

// Event returns the reusable runtime event.
func (w *GoldenEventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *GoldenEventWriter) Write(value *GoldenEvent, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

// WriteFunc constructs, encodes, and emits GoldenEvent only when enabled.
func (w *GoldenEventWriter) WriteFunc(value func() (*GoldenEvent, error), activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	return w.event.WriteIfEnabled(&w.binding, activity, related, func(*eventheader_gen_eventheader.Binding) error {
		if value == nil {
			return eventheader_gen_fmt.Errorf("event value function: %w", eventheader_gen_eventheader.ErrInvalidValue)
		}
		eventValue, err := value()
		if err != nil {
			return err
		}
		return w.bind(eventValue)
	})
}

func (w *GoldenEventWriter) bind(value *GoldenEvent) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	if len(value.Messages) > 65535 {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Messages: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	eventheaderGenSize1 := 2
	for i := range value.Messages {
		if len(value.Messages[i]) > 65535 {
			return eventheader_gen_fmt.Errorf("GoldenEvent.Messages: %w", eventheader_gen_eventheader.ErrCountTooLarge)
		}
		if eventheaderGenSize1 > 65467-2 || len(value.Messages[i]) > (65467-eventheaderGenSize1-2)/1 {
			return eventheader_gen_fmt.Errorf("GoldenEvent.Messages: %w", eventheader_gen_eventheader.ErrEventTooLarge)
		}
		eventheaderGenSize1 += 2 + len(value.Messages[i])*1
	}
	if len(value.NamedBlobs) > 65535 {
		return eventheader_gen_fmt.Errorf("GoldenEvent.NamedBlobs: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	eventheaderGenSize2 := 2
	for i := range value.NamedBlobs {
		if len(value.NamedBlobs[i]) > 65535 {
			return eventheader_gen_fmt.Errorf("GoldenEvent.NamedBlobs: %w", eventheader_gen_eventheader.ErrCountTooLarge)
		}
		if eventheaderGenSize2 > 65467-2 || len(value.NamedBlobs[i]) > (65467-eventheaderGenSize2-2)/1 {
			return eventheader_gen_fmt.Errorf("GoldenEvent.NamedBlobs: %w", eventheader_gen_eventheader.ErrEventTooLarge)
		}
		eventheaderGenSize2 += 2 + len(value.NamedBlobs[i])*1
	}
	if len(value.UTF16Text) > 65535 {
		return eventheader_gen_fmt.Errorf("GoldenEvent.UTF16Text: %w", eventheader_gen_eventheader.ErrCountTooLarge)
	}
	eventheaderGenSize3 := 2
	for i := range value.UTF16Text {
		if len(value.UTF16Text[i]) > 65535 {
			return eventheader_gen_fmt.Errorf("GoldenEvent.UTF16Text: %w", eventheader_gen_eventheader.ErrCountTooLarge)
		}
		if eventheaderGenSize3 > 65467-2 || len(value.UTF16Text[i]) > (65467-eventheaderGenSize3-2)/2 {
			return eventheader_gen_fmt.Errorf("GoldenEvent.UTF16Text: %w", eventheader_gen_eventheader.ErrEventTooLarge)
		}
		eventheaderGenSize3 += 2 + len(value.UTF16Text[i])*2
	}
	w.binding.Reset()
	if err := w.binding.UUID([16]byte(value.ID)); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.ID: %w", err)
	}
	if err := w.binding.UUIDArray(value.IDs[:]); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.IDs: %w", err)
	}
	if err := w.binding.Uint32(uint32(value.Code)); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Code: %w", err)
	}
	if err := w.binding.Bool(bool(value.Enabled)); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Enabled: %w", err)
	}
	if err := w.binding.String(string(value.Message)); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Message: %w", err)
	}
	if err := w.binding.Int64(int64(value.Elapsed)); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Elapsed: %w", err)
	}
	if value.Address.To4() != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Address: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	eventheaderGenIP4Slice := value.Address.To16()
	if eventheaderGenIP4Slice == nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Address: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	var eventheaderGenIP4 [16]byte
	copy(eventheaderGenIP4[:], eventheaderGenIP4Slice)
	if err := w.binding.IPv6(eventheaderGenIP4); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Address: %w", err)
	}
	if err := w.binding.Int32Array(value.Values[:]); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Values: %w", err)
	}
	if err := w.binding.BinaryArray(value.Blobs); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Blobs: %w", err)
	}
	if cap(w.eventheaderGenScratch1) < len(value.Messages) {
		clear(w.eventheaderGenScratch1)
		w.eventheaderGenScratch1 = make([]string, len(value.Messages))
	} else {
		if len(w.eventheaderGenScratch1) > len(value.Messages) {
			clear(w.eventheaderGenScratch1[len(value.Messages):])
		}
		w.eventheaderGenScratch1 = w.eventheaderGenScratch1[:len(value.Messages)]
	}
	for i := range value.Messages {
		w.eventheaderGenScratch1[i] = string(value.Messages[i])
	}
	if err := w.binding.StringArray(w.eventheaderGenScratch1); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Messages: %w", err)
	}
	if cap(w.eventheaderGenScratch2) < len(value.NamedBlobs) {
		clear(w.eventheaderGenScratch2)
		w.eventheaderGenScratch2 = make([][]byte, len(value.NamedBlobs))
	} else {
		if len(w.eventheaderGenScratch2) > len(value.NamedBlobs) {
			clear(w.eventheaderGenScratch2[len(value.NamedBlobs):])
		}
		w.eventheaderGenScratch2 = w.eventheaderGenScratch2[:len(value.NamedBlobs)]
	}
	for i := range value.NamedBlobs {
		w.eventheaderGenScratch2[i] = []byte(value.NamedBlobs[i])
	}
	if err := w.binding.BinaryArray(w.eventheaderGenScratch2); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.NamedBlobs: %w", err)
	}
	if cap(w.eventheaderGenScratch3) < len(value.UTF16Text) {
		clear(w.eventheaderGenScratch3)
		w.eventheaderGenScratch3 = make([][]uint16, len(value.UTF16Text))
	} else {
		if len(w.eventheaderGenScratch3) > len(value.UTF16Text) {
			clear(w.eventheaderGenScratch3[len(value.UTF16Text):])
		}
		w.eventheaderGenScratch3 = w.eventheaderGenScratch3[:len(value.UTF16Text)]
	}
	for i := range value.UTF16Text {
		w.eventheaderGenScratch3[i] = []uint16(value.UTF16Text[i])
	}
	if err := w.binding.UTF16Array(w.eventheaderGenScratch3); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.UTF16Text: %w", err)
	}
	if err := w.binding.Binary(value.Raw[:]); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Raw: %w", err)
	}
	if err := w.binding.Port(uint16(value.Detail.Count)); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Detail.Count: %w", err)
	}
	if err := w.binding.String(string(value.Detail.Text)); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Detail.Text: %w", err)
	}
	if err := w.binding.Binary(value.Data); err != nil {
		return eventheader_gen_fmt.Errorf("GoldenEvent.Data: %w", err)
	}
	return nil
}
