// Code generated by eventheader-gen; DO NOT EDIT.
// eventheader-gen syntax=1

package generateddep

import (
	eventheader_gen_fmt "fmt"
	eventheader_gen_sync "sync"

	eventheader_gen_eventheader "github.com/cataggar/LinuxTracepoints-Go/eventheader"
	eventheader_gen_userevents "github.com/cataggar/LinuxTracepoints-Go/userevents"
)

var (
	eventheaderGenGeneratedDependencyEventSchemaOnce  eventheader_gen_sync.Once
	eventheaderGenGeneratedDependencyEventSchemaValue *eventheader_gen_eventheader.Schema
	eventheaderGenGeneratedDependencyEventSchemaErr   error
)

// GeneratedDependencyEventSchema returns the immutable schema for GeneratedDependencyEvent.
func GeneratedDependencyEventSchema() (*eventheader_gen_eventheader.Schema, error) {
	eventheaderGenGeneratedDependencyEventSchemaOnce.Do(func() {
		eventheaderGenGeneratedDependencyEventSchemaValue, eventheaderGenGeneratedDependencyEventSchemaErr = eventheader_gen_eventheader.NewSchema(
			eventheader_gen_eventheader.SchemaOptions{Name: "GeneratedDependencyEvent", ID: 0, Version: 0, Tag: 0, Opcode: 0},
			eventheader_gen_eventheader.ArrayField(eventheader_gen_eventheader.Uint32Field("Values"), eventheader_gen_eventheader.ArrayFixed, 2),
		)
	})
	return eventheaderGenGeneratedDependencyEventSchemaValue, eventheaderGenGeneratedDependencyEventSchemaErr
}

// GeneratedDependencyEventWriter is goroutine-local reusable state for GeneratedDependencyEvent.
type GeneratedDependencyEventWriter struct {
	event   *eventheader_gen_eventheader.Event
	binding eventheader_gen_eventheader.Binding
}

// NewGeneratedDependencyEventWriter binds GeneratedDependencyEvent to provider. A writer must be used by only one goroutine.
func NewGeneratedDependencyEventWriter(provider *eventheader_gen_eventheader.Provider, storage []byte) (*GeneratedDependencyEventWriter, error) {
	schema, err := GeneratedDependencyEventSchema()
	if err != nil {
		return nil, err
	}
	set, err := provider.EventSet(4, 0x0, "")
	if err != nil {
		return nil, err
	}
	event, err := eventheader_gen_eventheader.NewEvent(set, schema)
	if err != nil {
		return nil, err
	}
	return &GeneratedDependencyEventWriter{event: event, binding: event.Bind(storage)}, nil
}

// Enabled reports whether the GeneratedDependencyEvent event is enabled.
func (w *GeneratedDependencyEventWriter) Enabled() bool {
	return w != nil && w.event != nil && w.event.Enabled()
}

// Event returns the reusable runtime event.
func (w *GeneratedDependencyEventWriter) Event() *eventheader_gen_eventheader.Event {
	if w == nil {
		return nil
	}
	return w.event
}

// Write encodes value and emits it with optional activity correlation IDs.
func (w *GeneratedDependencyEventWriter) Write(value *GeneratedDependencyEvent, activity, related *eventheader_gen_eventheader.ActivityID) error {
	if w == nil || w.event == nil {
		return eventheader_gen_userevents.ErrClosed
	}
	if !w.event.Enabled() {
		return w.event.Write(nil, nil, nil)
	}
	if err := w.bind(value); err != nil {
		return err
	}
	return w.event.Write(&w.binding, activity, related)
}

func (w *GeneratedDependencyEventWriter) bind(value *GeneratedDependencyEvent) error {
	if value == nil {
		return eventheader_gen_fmt.Errorf("event value: %w", eventheader_gen_eventheader.ErrInvalidValue)
	}
	w.binding.Reset()
	if err := w.binding.Uint32Array(value.Values[:]); err != nil {
		return eventheader_gen_fmt.Errorf("GeneratedDependencyEvent.Values: %w", err)
	}
	return nil
}
